docker/postgis/Dockerfile, docker/postgis/README.md, loader/src/sources/cvs/scraper.js
The reasons and use of these two components is not obviously clear to someone new to the codebase, so this adds some simple notices describing them.
=> Document PostGIS image & deprecated scraper

loader/src/cli.js
The loader currently streams output data on STDOUT, but when run on an automated schedule and using `--send` to send data to the API, that results in *huge* logfiles that aren't really useful for solving most problems and are instead very costly to manage. To avoid those issues, using the `--send` option now prevents data from being written to STDOUT.
This is a little easier than directing the output to `/dev/null` in Docker, since we’d need to add a bash script for that, and would then need `dumb-init` or another init system, and then things just get a bit complicated. Not writing to STDOUT when sending via HTTP seems like a reasonable switch, and keeps things simple.
(I initially tried to do something a little fancier by adding an option to specify a file path to write output to, but …
=> Don't output to STDOUT if sending via HTTP

terraform/db.tf
=> Only specify a major version for the database engine

server/package-lock.json, server/package.json
Just what it says in the title! Updates the server to the latest AWS SDK.
=> Upgrade aws-sdk to 2.999.0

loader/package-lock.json, loader/package.json, server/package-lock.json, server/package.json
Resolves one minor vulnerability alert.
=> Update Jest to v27.2.4

ui/package-lock.json, ui/package.json
This started as an NPM audit to fix some security vulnerabilities, but required some major dependency updates, and I ultimately just wound up updating all the UI dependencies. I did some testing, but this is also pretty low risk since we are no longer really actively using or demoing the UI component.
=> Update UI dependencies

loader/test/albertsons.test.js, loader/test/support/nock-back-plugin.js
**This depends on #437.**
I discovered some issues with our Nock-Back plugin when I tried to *use* #437, and tried to find some solutions here. This might be OK, or might need a *little* more tidying up before merging.
=> Fix Nock-Back issues discovered with schema test

.github/workflows/ci.yml
#446 did not quite behave as expected when merging. This should fix it.
=> Fix linting when merging to main

loader/test/fixtures/nock/albertsons_should_output_valid_data.json
I realized I had a Nock-Back recording for Albertsons on my hard drive that was not actually in the repo! I think I must have forgotten to commit it as part of #438.
=> Add Nock-Back recording I missed in #438

server/src/db.ts
Today, in dumb things discovered in my git stash that I may as well commit. I think this was maybe a follow-on to #341? ¯\\\_(ツ)\_/¯
Always fun to have an opportunity to use fancy new(ish) operators!
=> Use the NULLISH COALESCER for prettier code

README.md, terraform/loaders.tf
Deploy @cmroberts’s loader from #452 (and add @cmroberts as a contributor)!
=> Deploy H-E-B loader

loader/src/sources/prepmod/index.js
This is a follow-on to #467 that makes it actually work.
=> Update existing locations from PrepMod

loader/src/sources/albertsons/corrections.js
I fixed one, and another showed up *while I was doing it.*
Fixes https://sentry.io/organizations/usdr/issues/2809052505
=> More irregular naming fun from Albertsons

loader/package-lock.json, loader/package.json, ui/package-lock.json
This updates dependencies in the loader and UI project that had security vulnerabilities.
=> Update vulnerable dependencies

loader/src/sources/riteaid/api.js, loader/test/fixtures/riteaid.api.test.json
Pretty much what it says on the tin. I still wish they would just put the time zone in the string. :(
=> Rite Aid API times are now in UTC

ui/package-lock.json, ui/package.json
=> Update UI dependencies, fix vulnerability

loader/src/sources/riteaid/api.js, loader/test/riteaid.api.test.js
In #529, we discovered Rite Aid had subtly changed the time zone of their datetimes, causing us to store incorrect `valid_at` times. This adds a little sanity checking (we should never see an update time in the future or too far in the past) to help defend against similar changes in the future.
It also separates the parsing code into a different function, since it's gotten fairly complex.
=> Add sanity-checking for Rite Aid update times

loader/package-lock.json, loader/package.json, server/package-lock.json, server/package.json, ui/package-lock.json, ui/package.json
I had held off on this for a while because I thought I read something about a significant formatting change in v2.5, but it doesn't seem like it actually affected any of our code.
=> Update Prettier to v2.5.1

loader/src/sources/albertsons/corrections.js
Just what it says in the title! Fixes https://sentry.io/organizations/usdr/issues/2809052505
=> Add another manual correction for Albertsons

loader/src/sources/albertsons/corrections.js
Should fix https://sentry.io/organizations/usdr/issues/2809052505
=> Add correction for another Jewel-Osco location

loader/src/sources/riteaid/scraper.js
The Rite Aid web API seems to be sending the slot list twice for some dates, which is causing us to expect more unique slot IDs than are actually in the data. This handles the issue and resolves https://sentry.io/organizations/usdr/issues/3082744963
=> Handle repeated dates in Rite Aid scraper

terraform/ecr.tf
=> Make Docker image tags immutable in ECR

docs/incidents/2022-04-15--no-update-external-ids.md
Pretty much just what it says on the tin!
=> Add incident report for today's issue with updates

loader/src/sources/albertsons/corrections.js, loader/src/sources/albertsons/index.js
Fixes https://sentry.io/organizations/usdr/issues/2809052505
=> Fix Albertsons 276 (pediatric) listing

.github/workflows/ci.yml
Manually doing multiple steps, and waiting for the right timing is both frustrating and error-prone. I should have long since just automated deployment from `main`.
=> Automatically deploy in CI workflow on main branch

loader/src/sources/albertsons/corrections.js
This solves https://sentry.io/organizations/usdr/issues/2809052505 for now, although I still need to finish and solve this better in #677.
=> Add corrections for two Albertsons stores

loader/src/sources/heb/index.js, loader/test/fixtures/nock/h-e-b_should_output_valid_data.json
Pretty much just what it says in the title. Fixes https://sentry.io/organizations/usdr/issues/3359245720
=> Support early pediatric Moderna for H-E-B

loader/src/utils.js, loader/test/utils.test.js
Fixes https://sentry.io/organizations/usdr/issues/3367174815
=> Support WA's name for Moderna ages 0-5

loader/src/utils.js, loader/test/utils.test.js
Fixes https://sentry.io/organizations/usdr/issues/3382842420.
=> Support new Moderna 6-11 description in WA

.github/workflows/ci.yml
=> Trying out GitHub's new Actions job summaries

server/src/db-client.ts
In #781 I added logging for the size of the database connection pool(s). I realized later that DataDog offers a `gauge` metric that lets us graph and solve this use case much better. https://docs.datadoghq.com/metrics/types/?tab=gauge#definition
=> Use gauge instead of logging to track DB conns

loader/src/sources/njvss/index.js
I messed this up in #790 (clearly I didn’t test as well as I thought I did!).
Fixes https://sentry.io/organizations/usdr/issues/3479038899
=> HOTFIX: Use csv-parse v5 correctly

.github/dependabot.yml
I’ll turn off Snyk once this is merged.
=> Switch NPM and Docker updates to Dependabot

.github/workflows/ci.yml, .github/workflows/ui-deploy.yml, loader/src/exceptions.js, loader/src/sources/cdc/api.js, loader/src/sources/cvs/api.js, loader/src/sources/cvs/scraper.js, loader/src/utils.js, loader/test/api-client.test.js, server/src/api/edge.ts, server/src/db.ts
There are a number of new niceties we should be taking advantage of in the version of Node.js we are using (and more in 18, when we upgrade).
=> Use new JS languge features in Node 16

loader/src/sources/wa-doh.js
This fixes a bug introduced in #834.
=> HOTFIX: handle empty responses from WA DOH

server/scripts/merge-locations.js
Noticed this issue while doing a little cleanup around #459.
=> Ensure merging keeps public locations public

render.yaml
=> Set univaf.usdigitalresponse.org to point to Render

render.yaml
As expected, #905 did not work. I’ll have to manually create a new database to test this.
=> Try downsizing Render database, take 2

render.yaml
Another minor item coming out of review (on #779) with @alexallain.
=> Reduce max API server instances on Render

server/src/datadog.ts
While reviewing the improved metrics from #915 earlier today, I noticed that a lot of external requests have no route, which turns out to be because the static file server doesn't count as a route (or routes). For example, `/docs/` will wind up with no route in our metrics.
I tried to remedy the issue somewhat by filling in the requested URL (minus the querystring) when there’s no matched route, but realized that needs some guardrails — every tag value (and combination of tag values) counts as a metric we have to pay for, so if we allow any URL here, our DataDog bill is likely to blow up. I used status code < 300 (success & not a redirect) or status >= 500 (an error on our part, not the client’s) as a signal that the URL is likely legit and worth recording, although it’s certainly …
=> If there's no route, tag metrics with URL path

loader/src/sources/njvss/index.js
These new strings are based on work from @dhcole. This also changes things so we get an alert when new strings show up, which we did not before.
=> Update NJVSS loader with new vaccine types

loader/src/sources/wa-doh.js, loader/src/utils.js, loader/test/utils.test.js
The WA Dept. of Health source appears to have stopped finding new data sometime after October 1, which I only noticed as part of cleaning up all the cron problems we were having on Render.
I fixed the immediate issue (a piece of code started causing us to bail out early), added a notification if the source finds nothing, and then had a to fix a bunch of other issues (the way they source Costco data appears to have changed, along with how we have to find store numbers and the names of available products).
=> Washington DoH source is in bad shape

terraform/networks.tf
Give names to our VPC and networks so we can see what's going on in the AWS console.
=> AWS again: name VPCs and networks

terraform/api.tf
I figured #1016 would break because it needed this, and it did!
=> AWS again: set task role appropriately

terraform/db.tf
D'oh! Forgot this in the last two updates.
=> AWS again: allow ECS security to talk to DB

loader/src/metrics.js
I'm just making some real messes today.
=> Add missing file from #1025

terraform/api-domains.tf
Update origin names to match with CloudFront distribution names for Render. So many little fiddly bits here. :\
=> Update CloudFront origin names

loader/src/api-client.js, loader/test/api-client.test.js
In #1061 and #1062, I ran into some dumb issues with retries in the `ApiClient`. After some testing, the problem became obvious: `POST` requests don't retry by default. That's reasonable, and I probably should have assumed that was the problem in the first place, although the got docs have [an example of doing replies on a POST without first configuring that to be ok](https://github.com/sindresorhus/got/tree/v11.8.3#hooksbeforeretry) (I even wound up trying this and realized the example is just broken)! So I blame this on an incorrect manual, too. 😉 
This also adds tests so I can’t make the same very dumb mistake I made in #1061.
=> Actually fix retry issues in ApiClient

server/package-lock.json, server/package.json
Release notes:
- 7.16.0 https://github.com/getsentry/sentry-javascript/releases/tag/7.16.0
- 7.17.0 https://github.com/getsentry/sentry-javascript/releases/tag/7.17.0
- 7.17.1 https://github.com/getsentry/sentry-javascript/releases/tag/7.17.1
- 7.17.2 https://github.com/getsentry/sentry-javascript/releases/tag/7.17.2
- 7.17.3 https://github.com/getsentry/sentry-javascript/releases/tag/7.17.3
=> Upgrade Sentry to v7.17.3 in /server

.github/workflows/ci.yml, .github/workflows/ui-deploy.yml, loader/Dockerfile, render.yaml, server/Dockerfile
Includes several security vulnerability fixes, including an OpenSSL DOS.
=> Upgrade Node.js to v16.18.1

package-lock.json
I screwed up the lockfile in #1256.
=> Fix lockfile for Jest 29.4.1

loader/src/api-client.js
The loaders can send pretty significant amounts of data to the API server, so there's potentially a lot to be gained from compressing it. We already support compressed POST bodies on the server, so all that needs to happen here is telling the loader's client to compress when sending. Unfortunately Got only has built-in support for compressed responses, not requests, so this is a little bit manual.
(While cleaning up old Render.com, I noticed that we are incurring serious costs from traffic going through our NAT Gateways on AWS. I’m not sure whether this is the cause, but it seems like an easy and obvious improvement to make. I’m adding some monitoring in other PRs to get a better sense of what’s going on there.)
=> Compress data sent from the loaders

terraform/networks.tf
Step 2 of #1327. This removes the NAT Gateways that have been providing internet access to the private subnets, since we no longer run any services that need internet access in those subnets. They are now only for running services that are completely scoped to our VPC.
=> Remove NAT Gateways from private subnets

terraform/cron-loaders.tf
I added this a couple weeks ago, but never turned it on! Time to see how it runs.
=> Experimentally turn on riteAidSmart source

terraform/cron-loaders.tf
Activate the scraper added in #1465. Fixes #1460.
=> Turn on the new Albertsons scraper

.prettierignore, loader/src/sources/cvs/scrape-cvs-stores.js, loader/src/sources/kroger/scrape-kroger-stores.js
This is pretty analogous to the scrapers we wrote a while back to get all Albertsons stores. I wrote these during the mess around #1458 and #1459, and have had them just sitting uncommitted for a while. In the end, they weren't worth working more on since we are ramping things down, but they would probably be useful for anyone who might want to make use of the scrapers and tools in this codebase, so I felt it was worth committing for posterity and archival purposes.
=> Add store list scrapers for CVS, Kroger

README.md, docs/runbook/README.md
Add a notice about the maintenance status of this project to the README.
Fixes #1550.
=> Shutdown: Add maintenance notice to README
