- loader/package-lock.json
- loader/package.json
This includes a couple major version updates. I've checked the release notes and tested in order to ensure things are compatible. It supersedes a few pull requests from Snyk (#284, #286).
The only package this does not update is Prettier, since it contains changes that would format our code differently (https://prettier.io/blog/2021/05/09/2.3.0.html). I’ll leave that for a later time, and we should probably do it across all projects at once.
> Update loader dependencies

- docs/incidents/2021-06-29--actions-budget-terraform-state.md
This is an incident report covering the GitHub Actions budgeting and Terraform state issues that prevented us from effectively deploying hotfixes to the codebase on 2021-06-29.
> Add incident report for deploy issue on 2021-06-29

- server/package-lock.json
- server/package.json
- server/public/docs/openapi.yaml
- server/src/config.ts
- server/src/interfaces.ts
- server/src/smart-scheduling-routes.ts
- server/test/lib.ts
- server/test/smart-scheduling.test.ts
This vastly improves our implementation of the SMART Scheduling Links standard. It follows the new section with features designed for aggregators and also adds actual slots or daily capacity where we have them, now that we have top-level fields for that info.
- Fixes identifiers to use the new `external_ids` format.
- Simplifies location and schedule IDs.
- Adds last updated time to locations.
- Adds the `has-availability` extension on schedules instead of the wonky way we used to handle unknown availability.
- Adds `lastSourceSync` meta extension.
- Lists actual individual slots instead of one placeholder slot per location. If we don't know slots but do know daily capcity, that's used to create slots instead.
- Adds booking phone and deep link on slots.
- Adds capacity on slots.
- …
> Improve SMART SL API, use new aggregator guidance

- server/migrations/20210722181933_unpadded_ext_ids.js
This PR creates `external_id` entries for CVS stores that currently are shaped like `07000` but also may show up in other places as `7000`. This way we catch both formats.
Fixes #308
> Create migration to add unpadded store ids for CVS locations

- terraform/loaders.tf
Appointments aren't disappearing on a minute-by-minute basis anymore, so it probably doesn't make sense to run the loaders a whole lot more frequently than every five minutes at this point. This should also reduce costs *slightly*.
(Another other simple cost reductions we could do in this vein is combining loaders into a single run.)
> Don't run loaders more frequently than 5 minutes

- loader/src/cli.js
- loader/src/index.js
- loader/src/sources/vts/geo.js
- loader/src/utils.js
- loader/test/fixtures/vts.geo.test.json
- loader/test/utils.test.js
- loader/test/vts.geo.test.js
This PR sets up a new loader module `vts.geo` intended to update our geolocation data from Vaccinate the States's API. For the sake of more narrowly solving #236, it only works for Rite Aid and CVS locations, however I don't know of a reason why it wouldn't work for everything.
In addition to updating the `provider_location.position` field, it also may update `provider_location.name` if there is a mismatch. Most of our names *don't* match, but I did some regular expression hacking to try to get easy ones to align. To be honest, I wish it didn't touch the names, but the server requires sending one.
I haven't written any automated tests, yet. I'm not sure what would be best to test here. I did manually test this somewhat extensively, though. For the most part it does the right thing. …
> Load geographic coordinates for Rite Aid and CVS

- loader/package.json
- loader/src/index.js
- loader/src/sources/cdc/api.js
This PR is an approach to loading CDC data, and works with all of the states they support. For the sake of making sure we get good quality matches, it limits its current output to locations where we know the store number. Later on, we may be able to expand the number of locations loaded when we have more Vaccines.gov UUIDs in our system (perhaps from VtS data).
Fixes #300
> Add data loader for CDC

- terraform/loaders.tf
Subject says it all. @Mr0grog I'm not sure the timing matters much, but running it at 0GMT and 12GMT should put it far away from our nightly backup jobs
> Run CDC loader twice a day

- terraform/loaders.tf
We can kick off the task manually via the ECS dashboard.
> Create vtsGeo task (which never runs)

- terraform/loaders.tf
Now that the PrepMod loader works, let's start loading it! For now, the API is only turned on in Washington, and we are actively working to get it turned *back* on in Alaska, so this just runs it in those two states.
> Load PrepMod data from Washington and Alaska

- server/package-lock.json
- server/package.json
Fixes a minor security issue in path-parse (https://npmjs.com/advisories/1773), which is a subdependency of Knex.
> Update Knex & path-parse (a dependency) to 0.95.10

- loader/src/sources/vaccinespotter/index.js
- loader/test/vaccinespotter.test.js
- server/src/api/edge.ts
- server/test/api.edge.test.ts
This PR ensures that falsy values for `address_lines` don't cause unexpected errors by adding some server-side validation to coalesce those values into an empty array. It appears the only loader sending that sort of bad data was Vaccine Spotter, so we also apply a small fix there to clean up its output.
Fixes #355 from the server side as well as the loader side. Either fix would have sufficed, but both were easy, so 🤷🏽‍♂️.
> Handle invalid `address_lines` data (server and loader)

- server/src/db.ts
- server/test/db.test.ts
This PR addresses #223 by throwing an error if `:` is present in the `system` component of a `provider_location.externalId`. Note, this does not check if `:` is present in `value`.  
If `:` is present on create, the provider location is created without any external ids. If present on update, the original external Ids are preserved.
Let me know if there are any thoughts or feedback here!
Fixes #223
> Issue 223: Validate colon not present when saving provider_location.externalId

- server/src/app.ts
This route is meant for testing error handlers, and should not actually be available in production. (It doesn’t expose anything sensitive, but it can spam Sentry and make us thing something’s broken when it’s not.)
Fixes the second part of #358, alongside #375.
> Disable `/debugme` route in production

- server/src/app.ts
A few locations from the PrepMod loader are too big for our current 500 kB limit, so this is the quickest and straightest solution. We might want to do a second pass on the loader where we summarize the data more briefly, since this is a lot to ship *out* and to do joins on in our own API.
Fixes #387.
> HOTFIX: Bump max request body size in API server

- server/src/api/edge.ts
- server/test/api.edge.test.ts
Even if we're not updating the other properties of a location (name, address, etc.), we should always add any new external IDs we see for a location. This is a more reasonable thing than it used to be, since you can now only add to the list for a given location, and not change existing entries.
As we add and clean up a bunch of sources from VaccineSpotter, I’m a little worried we aren’t always capturing all the new IDs we’ve seen, and aren’t able to de-duplicate as effectively as we might otherwise (if one source silently fails to add a new ID, and another source uses it, we could wind up creating a new location record). A bunch of sources already set `update_location=true` ([for example, CDC](https://github.com/usdigitalresponse/univaf/blob/6eade8ea037b32bbecea074fe9d1d0eb2387859f/loader/ …
> Always update a location's `external_ids`

- loader/src/sources/vts/geo.js
- loader/test/vts.geo.test.js
This source is unsafe, and shouldn't be used until #433 is fixed.
> Prevent the `vtsGeo` source from running.

- loader/package-lock.json
- loader/package.json
- loader/src/sources/albertsons/index.js
- loader/src/sources/cdc/api.js
- loader/src/sources/riteaid/api.js
- loader/src/sources/wa-doh.js
- loader/test/albertsons.test.js
- loader/test/cdc.api.test.js
- loader/test/cvs.smart.test.js
- loader/test/kroger.smart.test.js
- loader/test/prepmod.test.js
- loader/test/riteaid.api.test.js
- loader/test/support/matchers.js
- loader/test/support/schemas.js
- loader/test/support/setup.js
- loader/test/wa-doh.test.js
- loader/test/walgreens.test.js
This adds an `expect(x).toMatchSchema(someJsonSchemaDefinition)` matcher to Jest in the loader project, and should be helpful in writing better tests.
There is a very nice [`jest-json-schema` package on NPM](https://www.npmjs.com/package/jest-json-schema), but it is [stuck on a several-major-releases-old version of AJV](https://github.com/americanexpress/jest-json-schema/pull/26). I wanted our schemas in the loader and server to be similar, and not have some weird edge cases because of AJV versioning problems, so I wound up just implementing something custom. At least it’s not super complicated, but still makes me sad. :(
The schemas are not the same as the server because:
- They needed to be more strict. The server ones are designed to help massage acceptable data into correct data, and …
> Add schemas for use in tests

- loader/src/model.js
- loader/src/smart-scheduling-links.js
- loader/src/sources/cdc/api.js
- loader/src/sources/prepmod/index.js
- loader/src/sources/wa-doh.js
- loader/src/utils.js
- loader/test/prepmod.test.js
- loader/test/support/smart-scheduling-links.js
- loader/test/wa-doh.test.js
- server/public/docs/openapi.yaml
- server/src/smart-scheduling-routes.ts
This adds two new product types:
- `pfizer_age_5_11` for the newly approved pediatric Pfizer vaccine for 5-11 year olds.
- `pfizer_age_2_4` for the still-in-testing pediatric Pfizer vaccine for 2-4 year olds. We *shouldn’t* be seeing this anywhere in practice, but there are official codes for it, and hopefully we’ll see it sooner or later.
And adds code to detect these for PrepMod, generic SMART SL sources, WA State Dept. of Health’s API, and the CDC’s Open Data. None of the other sources we know of support it yet.
I also discovered a few problems while doing this that I tried to fix:
- The WA DoH was failing to detect most vaccine types (the names changed)! We didn’t have its warnings hooked up for Sentry. 😱 
- We were using strings all over the place when we should have been using …
> Support Pfizer Pediatric Vaccines

- loader/src/sources/cdc/api.js
This fixes Walmart/Sam's Club support in the CDC source, and also adds support for:
- Shoprite
- Stop & Shop
- Sav-On
- Genoa Healthcare
- Bartell Drug
- Meijer
- Winn Dixie
- Hannaford
I focused on chains that are common in our partners' states (AK, NJ, WA) and that had lots of entries in the CDC data. I also did my best to make sure these external IDs seem sensible and match up to what we’ve already got (when we already have something for these stores). One exception here is Wegmans, which I couldn’t find a reasonable way to match up and wrote a big comment about inline.
I also tried to do this with minimal impact to the architecture of this source, but having this confined to the scope of a single external ID poses some problems, like store types that should really set more than one, …
> Expand store support in CDC API source

- loader/src/sources/njvss/index.js
Includes the string to determine whether a location has the pediatric 5-11 pfizer product.
This is not tested since I don't have univaf running locally, but the same implementation is working now on the NJ-hosted scraper.
> Parse pfizerAge5_11 vaccine product for NJVSS

- .github/workflows/ci.yml
- loader/src/cli.js
This removes pointless secrets (the test database is a test database and lives only for the lifetime of the workflow; there is no reason for it to have a secret password) and disable ECR login & docker push commands from even trying to run anywhere except `main` (which implicitly excludes PRs).
> Make CI workflow work from forks

- loader/src/api-client.js
- loader/src/cli.js
- loader/src/sources/prepmod/index.js
- loader/test/api-client.test.js
- loader/test/prepmod.test.js
- loader/test/support/smart-scheduling-links.js
- terraform/loaders.tf
We’ve had a lot of instances where a location in Alaska managed by PrepMod may initially be public, but is later marked private. This solves the problem by comparing the list of locations we already know about with the list of locations found in the PrepMod API, and marking any previously known locations as private if they didn’t show up in the PrepMod API.
This addresses #449 for PrepMod. It still needs to be propagated to other sources where it applies (CVS, Walgreens, Rite Aid, etc.).
A few other fixes came along for the ride here:
- `ApiClient.getLocations()` wasn’t respecting pagination! I think we used it in pretty constrained scenarios before (NJVSS) and never expected too many results. Honestly the situation is similar for PrepMod, but this felt worth fixing.
- Use the same …
> Hide locations that disappear from the PrepMod API

- loader/src/sources/cdc/api.js
Since we started logging CDC source errors to Sentry last week, we've been regularly getting errors about several Sam's Clubs with bad IDs in Puerto Rico (issue: https://sentry.io/organizations/usdr/issues/2771670374). This resolves the immediate error, although it really points to more significant refactoring that's needed in the CDC source.
> Special case Puerto Rican Sam's Clubs with bad IDs

- loader/src/sources/prepmod/index.js
- loader/test/prepmod.test.js
- server/public/docs/openapi.yaml
PrepMod provides an info URL that simply links to the front page of the PrepMod server, which includes *many* more locations than the one in question, or provides ultra-granular links to individual booking slots, which can be a bit hard for consumers to manage. In addition, it turns out some clinics have complicated vaccination patterns, like one in Alaska where Moderna is offered on certain days and J&J on others, but where the PrepMod API does not provide separate schedules for the two vaccines, so the product information on the slots is inaccurate and unhelpful.
This attempts to provide a happy medium by making the `booking_link` property on a location (the slot one is left as-is) that links to search results for the clinic. The caveat here is that searches are geographically based on …
> Provide a best-effort booking URL for PrepMod locations based on clinic search criteria

- server/package-lock.json
- server/package.json
We’ve had a bunch of unused dependencies floating around in the server that I’ve been meaning to eliminate for a while, so I finally did so. It removes:
- Async
- Bluebird
- Chai
- ShellJS
- Request
And also runs `npm audit fix` to resolve some minor security vulnerabilities in our dependencies.
> Remove unused dependencies in server

- loader/package-lock.json
- loader/package.json
- server/package-lock.json
- server/package.json
Just what it says on the tin. This supersedes #478 and #479.
> Upgrade Sentry to v6.15.0

- loader/src/model.js
- loader/src/sources/albertsons/index.js
- loader/test/albertsons.test.js
Albertsons started including a community clinic (presumably it’s being operated by a store pharmacy’s staff), which has been causing two errors in production:
- https://sentry.io/organizations/usdr/issues/2813365771
- https://sentry.io/organizations/usdr/issues/2809052505
This solves both of those issues by adding a new brand for “Community Clinic.”
It also fixes a follow-on issue that clinic alerted me to (but which was not unique to it): some pediatric clinics don’t indicate that they are pediatric in the name (but you can tell because they only list pediatric products), which some others have it in the name but list no products. Both of these are edge-casey, but do exist in the actual data.
> Handle community clinics in Albertsons data

- loader/src/sources/albertsons/index.js
Albertsons added another community clinic with a distinctly different name. This updates our matcher to handle it.
> Handle Albertsons "Castle Pines Vaccine Center"

- loader/src/sources/albertsons/index.js
- loader/test/albertsons.test.js
A few more community clinics popped up today, and I realized a better approach might be to match anything that doesn't look like `Some name ###`, since that is the pattern all the other brands follow. This will hopefully alert us if a new store chain shows up, but treat other things as community clinics.
> Match Albertsons community clinics generically

- loader/src/sources/albertsons/index.js
- loader/test/albertsons.test.js
This fixes an error while attempting to throw an error (ha!) that was captured here: https://sentry.io/organizations/usdr/issues/2830164846
And improves parsing to handle the source data that was causing it: a location in Idaha is missing a space before the dash that delimits the name from the address.
```
Albertsons 169- 909 E. Parkcenter Blvd., Boise, ID, 83706
```
It also groups by *unpadded* store number (instead of padded), since it turns out this problematic location is the accompanying pediatric version of another non-pediatric location with a padded store number.
> Albertsons name delimiters are definitely entered by hand

- loader/src/sources/prepmod/index.js
- loader/test/prepmod.test.js
This got a lot more complex than expected. Alaska is now including a shingles (zoster) vaccine in PrepMod, so we need to treat it like flu vaccines and ignore it.
While writing a test for that, I realized we weren’t correctly handling locations that only had non-COVID vaccines — we’d still include them, and set `availability` based on the non-COVID slots rather than COVID slots! That’s obviously pretty wrong. So this does a little bit of refactoring to determine whether a schedule is not actually a COVID schedule and skip over it (and its slots) if not, and drop the location if all its schedules are non-COVID ones.
> Alaska has shingles (vaccines)

- README.md
- loader/src/sources/riteaid/scraper.js
- loader/src/sources/riteaid/zip-codes.js
Thanks to @tmcw who helped with some code to narrow down a complete list of zip codes into a smaller list of fitting candidates.
I also discovered that Rite Aid has closed a few stores over the last couple months, including *every store in Colorado:* https://www.riteaid.com/locations/co/grand-junction.html (Also I did a lot more work than necessary here, assuming there were plenty more stores I’d need to account for before discovering there were only 3. 🤦)
> Add remaining zip codes for Rite Aid Scraping

- loader/src/sources/wa-doh.js
- server/migrations/20211213181430_hide_invalid_washington_prepmod_location_in_missouri.js
It looks like WA DoH has some bad PrepMod data in their DB. This fixes the issue by:
- Adding the location as to our list of bad data exceptions.
- Skipping over PrepMod-sourced data entirely when importing from WA DoH (since we already get it direct from PrepMod).
- Using a migration to hide the bad data in our DB.
> Remove bad PrepMod location data from WA DoH

- loader/src/sources/prepmod/index.js
The PrepMod API in Alaska is now surfacing vaccines for "Adenovirus." Based on context, these appear to be vaccines *agains* Adenovirus, not vaccines *using* Adenovirus as a delivery mechanism, so we should be OK to ignore them. Fixes https://sentry.io/organizations/usdr/issues/2876457061.
> Don't include "Adenovirus" vaccines in PrepMod

- scripts/deploy_infra.sh
Deploy commits now cover both the Loader and Server.
> Remove "server" from deploy commit message

- loader/src/sources/albertsons/corrections.js
- loader/src/sources/albertsons/index.js
- loader/src/utils.js
- loader/test/albertsons.test.js
- loader/test/utils.test.js
This makes two changes to resolve issues in Albertsons data right now:
1. Skip over locations with obviously invalid addresses (e.g. `., ., TX 75244`). There are two of these right now, and they currently parse “successfully” because they have an address-like structure. I’m betting they don’t refer to an actual location (the name for both of them is “Dallas ISD” which is probably the Dallas Independent School District), and if someone tried to book them, it’s not really clear where they would actually go (clicking through to the booking screen doesn’t provide any more useful information to clarify what or where this location is supposed to be). This will still emit warnings for bad addresses, but at least we won’t surface them in final data, and the issue is clearer.
2. Add manual …
> Albertsons data just gets funkier and funkier

- loader/src/sources/albertsons/corrections.js
Two Safeway locations recently started showing up with their pediatric listing using "Peds" where we'd normally have a store brand name. For example, instead of this:
Safeway 2624 - 3602 W. 144th Ave., Broomfield, CO, 80023
We are seeing:
Peds 2624 - 3602 W. 144th Ave., Broomfield, CO, 80023
It looks like someone lazily put in “peds” as short for “Pediatrics” in the store name. This uses manual corrections to handle the problem, since I'm wary of assuming that this will only ever happened for Safeway and not for other Albertsons brands.
Fixes https://sentry.io/organizations/usdr/issues/2809052505
> Fix error for Safeways named "Peds" in Albertsons

- loader/src/sources/cdc/api.js
- loader/src/sources/njvss/index.js
- loader/test/cdc.api.test.js
- server/src/db.ts
- server/test/db.test.ts
Over the weekend, the CDC’s open data on vaccine stock started surfacing duplicate locations for 113+ Walmarts and Sam’s Clubs. We previously saw locations with a `loc_store_no` like `10-NNN`, but are now seeing locations witha `loc_store_no` of `Not applicable`, but a parseable store number is in the name, and that store number is in the format `NNN` (i.e. no `10-` prefix).
Unfortunately, it’s not that the formatting *changed*, just that it’s different, and there are now many stores with two different `provider_location_guid` values for the same actual store (where each GUID has one of the two above formats). This handles the issue by making two major changes:
1. Makes these new store formats parseable in the CDC source.
2. Adjusts the server to allow multiple availability updates for …
> Handle new duplicate Walmart/Sam’s Club entries from CDC gracefully

- loader/src/sources/albertsons/index.js
- loader/test/albertsons.test.js
While cleaning up duplicate Walmarts in #519, I discovered some duplicate zero-padded/unpadded Albertsons that appear to have been caused by us not unpadding external IDs we send from the Albertsons loader (it turns out some entries are zero-padded and some not, and sometimes the pediatric and non-pediatric entries for the same location have different padding).
> Send/store unpadded store numbers for Albertsons

- loader/src/sources/albertsons/index.js
- loader/src/utils.js
Albertsons has a system where pediatric and non-pediatric bookings are sometimes separate entries/URLs. Since they represent the same location, We try and merge these, and to sanity check, we stop and warn if we are trying to merge two adult or two pediatric locations.
However, we've been getting a lot of these warnings intermittently, and the core of the problem really seems to be that, in contrast to when pediatric vaccines first showed up, many pediatric entries now list *both* adult and pediatric vaccines, alongside another entry that is adult-only. This fixes the warnings by classifying a location as pediatric if *some* of the vaccines are pediatric, instead of only if *all* are.
While I was at it, I also added some depth to the logging about this situation, since the actual vaccine …
> Change how Albertsons locations qualify as pediatric

- terraform/loaders.tf
Their data format changed, and we are now declaring locations as unavailable when in fact they are. This disables the scraper for now.
> Temporarily disable Rite Aid scraper

- loader/src/sources/albertsons/corrections.js
- loader/src/sources/albertsons/index.js
- loader/test/albertsons.test.js
Albertsons continues to get messier and with looser naming conventions. 😭
This adds a bunch of manual corrections, plus additional logic to support or throw errors for:
- More pediatric name prefixes.
- A Teamsters union office location.
- Skip non-real/test locations that are in the production data. I think there’s just one.
- Throw errors for locations that have a URL for their name/address (!), e.g. “https://kordinator.mhealthcoach.net/vcl/1636075700051 - Vons - 3439 Via Montebello, Carlsbad, CA, 92009”
- Don’t treat locations starting with numbers as community clinics. We had a lot of bad names we should have been creating exceptions for like "108 Pediatric Pfizer  - 1735 Artesia Blvd., Gardena, CA, 90248" (should be “Albertsons 108 - 1735 Artesia Blvd., Gardena, CA, 90248”). They …
> Add a whole bunch more exceptions and exception logic to Albertsons

- loader/src/cli.js
- loader/src/sources/riteaid/api.js
- loader/src/utils.js
We have an issue where the Rite Aid API loader will often have an error on a request for a state’s data and stop, instead of continuing on to try the rest of the states. This handles that, and sends better error info to Sentry to boot.
It also adds rate limiting support.
> Keep trying additional states if Rite Aid API fails on one

- terraform/loaders.tf
Now that it’s fixed, let’s turn it on.
> Re-enable the Rite Aid scraper

- terraform/loaders.tf
In #531 we added better logging and handling of Rite Aid API HTTP errors, and it seems clear that we just don't have permission to load data for Colorado, so we may as well turn it off (we still get data for CO via the scraper, so this is not totally horrible).
> Stop using Rite Aid API in Colorado

- loader/src/sources/albertsons/corrections.js
This fixes two more problematic locations with Albertsons, and solves https://sentry.io/organizations/usdr/issues/2809052505.
One location had a name starting with “12 & Up”. It was a community clinic, and I struggled with whether to allow it in the community clinic brand matcher, but ultimately worried it would be too broad, so I just added a manual correction for it. For posterity in case I need it later, the code I didn’t use was:
```js
{
...BASE_BRAND,
key: "community_clinic",
name: "Community Clinic",
locationType: LocationType.clinic,
pattern: {
test: (name) => {
return (
// Disallow locations that look like "name followed by store number"
// (these should probably be actual store brands) or that just start
// with a big block of numbers (these just seem broken). …
```
> Fix two more location issues with Albertsons

- loader/test/utils.test.js
This test has been a little flaky and sometimes fails out of the blue because the RateLimit timer resolved in 999 milliseconds instead of 1000. That should really be fine.
> Allow for more jitter in RateLimit test

- .eslintrc.js
- loader/src/__mocks__/utils.js
- loader/src/schema-validation.js
- loader/src/sources/riteaid/api.js
- loader/src/sources/riteaid/common.js
- loader/src/sources/riteaid/scraper.js
- loader/src/utils.js
- loader/test/fixtures/riteaid.api.test.json
- loader/test/riteaid.api.test.js
- loader/test/riteaid.scraper.test.js
- loader/test/utils.test.js
I thought this wouldn’t be too complex, but alas, I was wrong, as usual.
This is a follow-on to the Rite Aid API issues discovered while counting slots last week in https://github.com/usdigitalresponse/appointment-data-insights/pull/3. The main idea was to check the number of slots the API is reporting to make sure it’s reasonable (since it was reporting thousands per store for a couple months). Of course, as I got into it, it expanded:
- Check the number of slots to make sure the total is reasonable (this only triggers a warning, since it’s possible our definition of “reasonable” could be bad).
- Check the slots to make sure it’s not reporting mismatching values, i.e. where the available slots are more than the total slots. This causes an actual error, since this would seem to indicate …
> Add more validation to Rite Aid API

- loader/src/sources/albertsons/index.js
We've been logging errors for two Albertsons/MHealth locations with the nonsense addresses:
., ., TX, 75211
., ., TX, 75244
I left them as an error under the assumption they were a mistyped entry that would get corrected (you can even see it when you search for appointments by zip code in their UI!), but it never did. At this point, I assume it's intentional (Dallas ISD is probably the school district -- Dallas Independent School District -- and I'm guessing these are for tracking vaccinations across the district, so someone probably did this because a particular address was not releveant).
It's filling up our error logs and charts and making it hard to see less common errors, so this change just makes us skip the location before we even try to parse these nonsense addresses.
> Ignore Dallas ISD locations with nonsense addresses

- terraform/provider.tf
Our current deployment is failing because Terraform upgraded the default release of the AWS provider, and that upgrade included breaking changes. This locks our version for now so we can deploy, and we'll remediate separately.
> Explicitly specify AWS Terraform provider version

- .github/dependabot.yml
- terraform/provider.tf
This is a follow-on to #569. It turns out we were using an old method of configuring Terraform dependencies and versions that is deprecated. This updates it and adds Dependabot for for Terraform and actions (but not for NPM, where we are still using Snyk for now).
> Set up Terraform dependencies correctly

- loader/src/sources/riteaid/scraper.js
- loader/test/riteaid.scraper.test.js
I should have written a test for #592! I fixed one error, but wound up outputting duplicate entries in the list of products for slots that got repeated, which is invalid. This fixes the issue.
> HOTFIX: duplicate products in Rite Aid scraper

- server/migrations/20220315003750_correct_invalid_state_abbreviations.js
- server/src/db.ts
- server/src/interfaces.ts
- server/src/validation.ts
- server/test/api.edge.test.ts
- server/test/api.legacy.test.ts
- server/test/validation.test.ts
This adds some validation logic to the server that ensures we always store states in the form of a two-letter postal abbreviation (e.g. “AK” for Alaska). This is already what we mostly have, but there are a handful of locations that have come in from PrepMod with different names (e.g. “alaska” or “Alaska”; PrepMod appears to allow free-form data in the state field). The basic premise here is to accept any known identifier for the state (it‘s full name, a postal abbreviation, an ISO name, etc.) and replace that with the postal abbreviation, or return a 422 error if we don’t recognize the state that was passed in.
While I was at it, I went ahead and wrote a more generalized `validateLocationInput()` function that does a few other minor validations (it handles one we already had, and adds a …
> Ensure locations’ `state` is a two letter postal abbreviation

- loader/src/sources/albertsons/corrections.js
- loader/src/sources/albertsons/index.js
Albertsons has traditionally named all Sav-On pharmacies "Albertsons Pharmacy" in their data, but now some are surfacing as "Sav-On Pharmacy". This adds support for the new (old) branding.
The `sav_on` system name is the one we’re already using when we get these from CDC: https://github.com/usdigitalresponse/univaf/blob/d0477b1eb9e80d5b941ebc03e792d3fa99ac2656/loader/src/sources/cdc/api.js#L248-L250
One other thing worth noting here is that the above points to some de-duplication we might want to do: there are probably a lot of "Sav-On" locations from CDC that we have under a different name and ID from Albertsons.
> Handle Albertsons pharmacies with "Sav-On" brand

- loader/Dockerfile
- server/Dockerfile
- server/Dockerfile.seed-db
- server/package-lock.json
- server/package.json
- server/tsconfig.json
This upgrades us from v14 to v16 of Node.js, which adds some nice new JS/TS language features. I’ve also switched to `-slim` Docker images, but have not really tested out that they work yet. Need to do that before merging.
> Upgrade Node.js to v16.14.2 (latest LTS version)

- loader/src/sources/cdc/api.js
- loader/src/utils.js
- loader/test/cdc.api.test.js
- loader/test/utils.test.js
In #598 we added more robust schema checking for location data, and it turns out we were importing lots of not-quite-valid URLs from the CDC's dataset. Mainly these are just missing a scheme, e.g. "www.kroger.com" instead of "http://www.kroger.com". This adds a pretty simple routine for cleaning those up (and also handling leading/trailing spaces, etc.). It's simple enough that I didn't think an external dependency was worthwhile, but if we wanted to do more, then we should probably use something pre-built.
Fixes https://sentry.io/organizations/usdr/issues/3106483109 and https://sentry.io/organizations/usdr/issues/3106483083.
> Repair not-quite-valid URLs from CDC data

- loader/src/sources/albertsons/index.js
Albertsons now has a clinic at a Chicago Fire Department location, which uses a number (the firehouse number?), so it doesn't auto-identify as a community clinic. This adds a special case to support it, much like we did with the Teamsters Union hall.
Fixes https://sentry.io/organizations/usdr/issues/2809052505.
> Support Chicago Fire Department community clinics

- server/migrations/20220415193103_change_external_id_pk_to_bigint.js
We've exhausted every possible integer for the primary key to the `external_ids` table, and as a result, and no longer insert or update any rows in it. Changing the type from integer to bigint gives us some breathing room for the system to keep operating, although we should ideally follow this up with a solution that doesn't run through sequence values so fast.
The fundamental problem here is that we manage external IDs by atomically upserting them (i.e. using a `INSERT INTO ... ON CONFLICT DO UPDATE ...` query), and requiring that they be unique by `(provider_location_id, system, value)`. Before PG can check for conflicts, evaluate constraints, etc. to validate an upsert and check for conflicts, it has to fill in all the default values, etc. on a column. If a column is based on a …
> HOTFIX: Change external_ids primary key to bigint

- .github/workflows/ci.yml
- loader/test/fixtures/nock/h-e-b_should_output_valid_data.json
- loader/test/heb.test.js
- loader/test/server.test.js
- loader/test/support/nock-back-plugin.js
This makes sure Nock cannot connect to live servers and make new recordings during tests in CI, effectively ensuring that all HTTP requests in tests either:
1. Have saved recordings to use,
2. Have explicit mocks in code, or
3. Are explicitly allowed by test code.
Fixes https://github.com/usdigitalresponse/univaf/issues/454.
> Fail CI if Nock.back recordings are missing

- loader/src/sources/prepmod/index.js
- loader/test/prepmod.test.js
We are now seeing vaccines named "Child and Adolescent Immunization(s)" in Prepmod, and this adds support for that. Fixes https://sentry.io/organizations/usdr/issues/3206105433
> Support a new generic vaccine name in Prepmod

- loader/src/sources/cdc/api.js
- loader/src/sources/riteaid/api.js
- loader/src/sources/riteaid/common.js
- loader/src/sources/riteaid/scraper.js
- loader/test/cdc.api.test.js
- loader/test/riteaid.api.test.js
- loader/test/riteaid.scraper.test.js
In hindsight, I probably should have seen this coming. Rite Aid bought Bartell back in 2020, and it looks like they may be starting to integrate systems — Bartell data is showing up in Rite Aid’s booking website backend, causing our scraper to break. See Sentry issue: https://sentry.io/organizations/usdr/issues/3141140661.
Unfortunately, we already have most Bartells via the CDC’s data portal, and we have them stored with a Bartell-specific ID rather than a Rite Aid-wide ID.
However! We happen to know that Rite Aid’s IDs are in the form `"<brand-based-prefix><brand-based-ID>"`, so we can use this appropriately determine both an ID for both the `rite_aid` and `bartell` external ID systems, and make sure all the right records get merged together. 🎉
The code on the CDC side is a little …
> Handle Bartell stores showing up in Rite Aid APIs

- server/scripts/merge-locations.js
I ran into an issue with an entry that had no address while merging Rite Aid and CDC data as a follow-up to #654. This changes the merge scripts to account for and handle it appropriately.
> Make addresses optional in merge script

- terraform/api.tf
These are based on recommendations from Snyk. It flags a whole range of minor-to-midgrade vulnerabilities in our Terraform configs, but a lot of them don’t feel relevant, e.g. our public S3 bucket is public! But these two seemed like good small things to fix.
> Security tweaks for Terraform API module

- loader/src/sources/albertsons/index.js
Fixes the fatal error in https://sentry.io/organizations/usdr/issues/3298819475. The error was intermittent, so I can’t investigate deeper as to whether some other mistake was triggering it, but seeing as we made `adult` an optional value in the next line, I think this was just an oversight.
> Handle Albertsons locations without adult vaccines

- loader/src/sources/albertsons/corrections.js
- loader/src/sources/albertsons/index.js
- loader/test/albertsons.test.js
This is *way* not ideal, but there are now a whole mess of locations from Albertsons without store numbers in the address. The best I could think to do without massive change here is a bunch of overrides, but I have a feeling we’re going to see more of these, and will have to come up with something fancier.
> Clean up messy new names for Albertsons pediatric booster locations

- loader/src/sources/albertsons/index.js
It looks like whoever is listing vaccine appointments for Albertsons is now using "ABS" to abbreviate "Albertons Pharmacy" for a lot of locations. Fixes https://sentry.io/organizations/usdr/issues/2809052505.
> Support "ABS" as an abbreviation for Albertsons

- loader/src/sources/albertsons/corrections.js
Ran into this while testing for #677. It has two addresses plugged together: `942 S York Rd Elmhurst 60126 IL, La Grange Park, IL, 60526`. (The section before the address indicates the clinic is in Elmhurst, so I went with that part of the address.)
> Add another Albertsons special case

- loader/src/sources/albertsons/index.js
Discovered while testing #677. It turns out we have a few community clinics getting classified as United Supermarkets. 😓
Example: `First Tongan United Methodist Church  - 560 El Camino Real, San Bruno, CA, 94066`.
> Use more detailed pattern for United Supermarkets

- loader/src/sources/cdc/api.js
- loader/test/cdc.api.test.js
When Walmart stores had a store number in the name (instead of in the store number field), they used to be formatted as "Walmart NNN" (where N is a digit). Some are now appearing with a "10-" prefix, e.g. "Walmart 10-0178" (the same format as in the store number field). This alters our parser to handle both.
Fixes https://sentry.io/organizations/usdr/issues/3338103303.
I also fixed a geographic position validation bug I noticed while I was addressing the above issue.
> Handle new Walmart store name formatting from CDC

- loader/src/sources/albertsons/corrections.js
Found while doing follow-on cleanup for #677. This location has bad geocoding that causes it to match to an entirely different Jewel-Osco 10 miles away.
> Add correction for Albertsons 1643755181825

- loader/src/sources/cdc/api.js
New `00069-2025-*` NDC codes started showing up in CDC's data today. They aren't (yet?) listed on CDC's COVID-19 codes page, but are listed on the complete crosswalk of all vaccines. These are for Comirnaty (the sales name for Pfizer's vaccine), so appear to effectively replace the `00069-1000-*` codes.
(More technically: `0069-1000-*` was for a version of the vaccine that was licensed but never manufactured, and we don’t appear to have ever seen it used in practice. `00069-2025-*` is a the newer tris-sucrose formulation of the same vaccine, which appears to finally be getting manufactured and sold now.)
Fixes https://sentry.io/organizations/usdr/issues/3342633674
> Support new `00069-2025-*` NDC codes

- server/.env.example
- server/src/app.ts
- server/src/config.ts
- server/src/middleware.ts
- server/src/smart-scheduling-routes.ts
- server/src/utils.ts
- server/test/app.test.ts
- server/test/config.test.ts
- terraform/api.tf
I’ve already created a new SSL certificate that handles both host names and deployed it, so these configs *should* be all that’s needed at this point. To create the SSL certificate I had to create a CNAME record already, so we’ll see what happens with Terraform here.
Fixes #302.
> Serve from www subdomain as well as no subdomain

- terraform/api.tf
This is a follow-on to #665, which failed to deploy because of this.
> Route 53 CNAME records must have a TTL

- server/src/app.ts
- server/test/app.test.ts
It turns out a redirect on the healthcheck endpoint is a failure, since it's not a 200 status code. Without this fix, ECS won't deploy our code, since it thinks the server is failing to run. :(
While I was at it, I also moved DataDog earlier in the stack, so we track errors that happen in middleware.
> HOTFIX: Don't redirect healthcheck to primary host

- server/src/middleware.ts
- server/test/app.test.ts
The primary host redirects we just added worked great in my testing, but do not seem to be playing nice with CloudFront and/or ELB (or maybe it’s because we have two levels of proxying there…?). This disables the redirects and adds logging in their place to see what’s going on.
> HOTFIX: Disable primary host redirects

- .github/workflows/ci.yml
We already did this for regular pushes, and it makes sense for PRs, too.
> Don't run CI jobs for terraform/docs only changes

- terraform/api.tf
Part of the problem in #706 is that the `Host` header is not getting forwarded by Cloudfront. This should solve that, although I suspect there might be some ELB rejiggering needed afterwards.
> Forward the Host header from Cloudfront

- terraform/api.tf
I thought I'd looked for a way to do this before and didn't see it, but while dealing with issues in the earlier approach, I found this. Hopefully this (plus #708, which this depends on) solves #302 in pretty much the ideal way.
If this works out, there’ll be some cleanup to do from the earlier approach.
> Implement `www.` → no subdomain redirect in ELB

- loader/src/sources/heb/index.js
- loader/test/fixtures/nock/h-e-b_should_output_valid_data.json
H-E-B is using `Ultra_Pediatric_Pfizer` to represent the new early childhood vaccine (6 months - < 5 years). They don't yet appear to have added anything for Moderna.
Fixes https://sentry.io/organizations/usdr/issues/3359245720
> Support H-E-B's new `Ultra_Pediatric_Pfizer` code

- server/src/app.ts
We are now seeing a handful of GIANT listings from PrepMod which appear to be legit, so this updates the allowed body size to handle them.
For example, a clinic in Puyallup, WA has 3897 slots (!) from 47 separate events (looks like a morning & afternoon event each Wednesday - Saturday) for the next 6 weeks. They’re really scheduling ahead (probably because of the new early pediatric vaccines).
> Increase POST body limit to 2.5 MB

- docs/runbook/README.md
Fixes #360 by adding an overview of other services we depend on that weren’t previously documented. Also adds more details about how we use ECS and updates how deploys work, since that’s changed significantly and was no longer accurate.
> Update main runbook docs

- loader/src/server.js
- loader/src/sources/cdc/api.js
- loader/src/sources/cvs/shared.js
- loader/src/sources/cvs/smart.js
- loader/src/sources/heb/index.js
- loader/src/sources/hyvee/index.js
- loader/src/sources/kroger.js
- loader/src/sources/njvss/index.js
- loader/src/sources/prepmod/index.js
- loader/src/sources/riteaid/api.js
- loader/src/sources/riteaid/scraper.js
- loader/src/sources/wa-doh.js
- loader/src/sources/walgreens.js
- loader/src/utils.js
- loader/test/albertsons.test.js
- loader/test/api-client.test.js
- loader/test/cdc.api.test.js
- loader/test/cvs.api.test.js
- loader/test/cvs.scraper.test.js
- loader/test/cvs.smart.test.js
- loader/test/heb.test.js
- loader/test/hyvee.test.js
- loader/test/kroger.smart.test.js
- loader/test/prepmod.test.js
- loader/test/server.test.js
- loader/test/smart-scheduling-links.test.js
- loader/test/vaccinespotter.test.js
- loader/test/vts.geo.test.js
- loader/test/wa-doh.test.js
- loader/test/walgreens.test.js
**This is a follow-on to/depends on #725.** Since I was updating logging, it seemed like it made sense to normalize everything. But I hadn’t realized how many loaders we never updated, and this turned into a *way* bigger job than expected. 😬
There is probably some good refactoring to be done on the logging tools, but that'll be easier after making everything use the tools we currently have.
This also sends a bit more context data to Sentry. I’m thinking we should just always do that instead of making it optional (I think I may have originally been under the impression that Sentry couldn’t take complex objects in the context, but [this test shows it actually works great](https://sentry.io/organizations/usdr/issues/3368356106/)), but that’s a refactor that should probably be reserved for a …
> Use the standard loader logger everywhere

- loader/src/sources/njvss/corrections.js
- loader/src/sources/njvss/index.js
This follows the pattern of corrections we added for Albertsons, and solves issues with a few bad addresses. (This was triggered by changes in #726, which put some of these ongoing address errors a little more in my face — which is a good thing.)
> Add manual corrections to NJVSS

- loader/src/model.js
- loader/src/sources/albertsons/index.js
Between authoring #734 yesterday night and merging today, the actual data has changed quite a bit. "infant" is no longer the only way that early childhood vaccines are indicated; listings now sometimes say pediatric (age 3-5). This modifies our expressions to match it and loosens some other checks that are no longer applicable.
Fixes https://sentry.io/organizations/usdr/issues/3376638147/
Here’s a quick report-out of how this identifies “infant” vs. “pediatric”: https://gist.github.com/Mr0grog/cf10c09b138a2318ce9c3f6b3ac703be
> Identify early child age range in Albertsons names

- loader/src/sources/njvss/index.js
In https://sentry.io/organizations/usdr/issues/3373843306, we're getting a warning because the NJVSS loader can't match an NJVSS location to one we've previously saved. It turns out this is because it has a different provider (`walmart`) which is pretty reasonable. The real problem is that we were only considering locations with NJVSS as a provider for matching, when we should instead be considering all locations in New Jersey.
> Match NJVSS locations with different providers

- server/src/db.ts
It turns out we have a lot of locations whose CDC data is dropping out of our availability listings because reporting frequency has dropped over time — they only report every few days, and the CDC only updates the public data once a day. Since a lot of locations don’t provide product info in their appointment listings, the CDC is a critical source for the `products` field and it makes sense to extend the timeframe we consider valid to contribute to the merged `availability` object.
Fixes #739.
> Extend availability merge window form 2 days to 7

- loader/src/sources/albertsons/index.js
- loader/test/albertsons.test.js
Albertsons has started using textual age ranges (e.g. "ages 5 to 11" instead of "ages 5-11"), which caused us to start seeing the "11" as a store number. This change makes our store-number-finding-regex a little more complex to not find numbers preceded by `" to "`, which solves the issue.
Fixes https://sentry.io/organizations/usdr/issues/3397100576.
> Handle new Albertsons age range format

- loader/src/utils.js
- loader/test/utils.test.js
Fixes https://sentry.io/organizations/usdr/issues/3382842420
> Support age ranges using `through` instead of `-`

- loader/src/sources/albertsons/index.js
- loader/test/albertsons.test.js
We were sometimes interpreting dates as store numbers for Albertsons, like the "10" in "July 10" from the entry named "Olympic Hills School Pfizer Clinic for ages 3+ July 10 9:30am-12:30pm". This updates our store number regex to avoid this situation.
This is a little ugly, and a better long-term fix is probably to include store numbers in the regex used to match brands (we don’t really need the part of this that cleans up the name, since we have the scraped store data now). That’s a big change I don’t want to land without a lot more testing, though.
Fixes https://sentry.io/organizations/usdr/issues/3397100576
> Avoid interpreting dates as store numbers

- terraform/modules/loader/main.tf
We've long known that the loaders are probably overprovisioned. This downsizes them by 50%. Partially covers #303.
See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_size for valid cpu/memory values and combinations.
> Downsize loaders to 0.5 vCPU, 1 GB RAM

- terraform/api.tf
This is a follow-on to #542. Apparently we weren't telling ECS what image tag to use for the daily-data-snapshot task, so we've never actually deployed new code to it. 😱
(I noticed this only because the run today did not write a `.gz` file!)
> Actually deploy updates to daily-data-snapshot

- server/src/availability-log.ts
- server/src/config.ts
- server/src/db-client.ts
- server/src/db.ts
- server/src/logger.ts
While addressing https://sentry.io/organizations/usdr/issues/3155794613, we realized we don't really have a handle on exactly how the database connection pools are behaving (see discussion in #778). This change logs every time the pool grows or shrinks, which should give us a better idea how the two pools are behaving. It'll log lines like:
```
2022-07-28T19:37:00.711Z [univaf] info: squarpix.lan Data DB pool size: 1
2022-07-28T19:37:00.714Z [univaf] info: squarpix.lan Data DB pool size: 2
2022-07-28T19:37:00.715Z [univaf] info: squarpix.lan Data DB pool size: 3
2022-07-28T19:37:31.763Z [univaf] info: squarpix.lan Data DB pool size: 2
```
Note: the hostname is included here (`squarpix.lan` in the example above) because we are usually running multiple instances of the server, and we need …
> Log changes to database connection pool size

- loader/src/sources/hyvee/index.js
HyVee started listing "Moderna (12-17)" as a vaccine type, but it's not actually a different product from what's used for ages 12+ or 18+. The location in question also lists some younger pediatric vaccines, so presumably this doesn't have anything to do with the minimum age the pharmacist is qualified for, and presumably there are just some appointment slots that are age limited this way.
I've classified these as normal `moderna` here, and that is probably a close enough approximation to make sense, rather than creating a new vaccine type for this weirdness (but if we want to there is the [someone-is-always-doing-something-weird](https://github.com/usdigitalresponse/univaf/compare/0605690...someone-is-always-doing-something-weird) branch). HyVee doesn’t have any locations in NJ or AK, so …
> Handle Moderna ages 12-17 listings from HyVee

- server/knexfile.js
- server/src/config.ts
- server/src/datadog.ts
- server/src/db-client.ts
- server/src/logger.ts
- server/test/datadog.test.ts
These are some minor monitoring improvements:
- Use global tags to make sure every metric gets platform and instance name info.
- Use metrics to track how backlogged the pool is by watching pending acquires and connection acquire time (in milliseconds).
This also updates the minimum pool size to be zero, per an earlier discussion with @astonm about [Knex’s defaults vs. recommended settings](https://knexjs.org/guide/#pool).
> Add more DB pool metrics, improve metric tagging

- render.yaml
- server/src/app.ts
- server/src/config.ts
- terraform/api.tf
- terraform/variables.tf
We've had Sentry's tracing tools in our dependencies for a while, but never gotten around to setting them up properly. This sets things up for the server (it doesn't address the loader since there's no built-in stuff and there needs to be a lot of work putting spans in all the appropriate places). There are probably a lot of places where we could put in spans for more detail, but this is a start.
> Implement Sentry tracing for API server

- loader/src/sources/albertsons/corrections.js
This locations was coming in with the address field `1094  - 1891 Pioneer pkwy, Springfield, OR, 97477`, which leaves the `1094` at the start pretty ambiguous. It turns out to be the store number for the Safeway in Springfield.
Fixes https://sentry.io/organizations/usdr/issues/3490953352.
> Manually correct another Albertsons address

- loader/src/utils.js
- loader/test/utils.test.js
Listings in Alaska's PrepMod instance are starting to show up as "Comirnaty" instead of "Pfizer" or "Pfizer (Comirnaty)", so we need to make sure it works for fuzzy matching of names. Fixes https://sentry.io/organizations/usdr/issues/3382842420
> Support "Comirnaty" as a vaccine name

- render.yaml
- terraform/variables.tf
We hit the transaction limit in Sentry less than a week after I turned on performance monitoring (#794). This drops us down to a much more minimal sample rate (we can adjust back up later as appropriate or if/when we turn off either the ECS or Render deployments.
> Reduce default Sentry sample rate

- loader/src/sources/prepmod/index.js
- loader/test/prepmod.test.js
Alaska's PrepMod instance is now surfacing Jynneos (Monkeypox vaccine). This ignores it like we do other non-COVID vaccines.
Fixes https://sentry.io/organizations/usdr/issues/3382842420.
> Ignore Monkeypox vaccines in Alaska

- server/package-lock.json
- server/package.json
- server/src/server.ts
We used to shut down the server gracefully on SIGINT, but not SIGTERM. However, SIGTERM is what shuts us down in production, which is arguably the time at which we need to be more graceful! This sets up graceful shutdown for several relevant signals.
It also makes sure we destroy availability logging connections during shutdown (not just normal data connections). This isn't a *huge* deal, since these connections would get reaped pretty quickly when the process dies anyway, but this should make things a little nicer on the DB.
> Graceful shutdown in production

- render.yaml
- server/.env.example
- server/src/config.ts
- server/src/db-client.ts
We need to manage our database connections on Render more carefully (the limits are *much* lower), and this gives us the ability to configure the connection pool size for regular DB connections vs availability log connections separately. It also configures the availability log connections to have a smaller pool size (5, rather than 10) since there is usually much lower contention for them.
Fixes https://sentry.io/organizations/usdr/issues/3155794613 and is an alternative to #778, based on @astonm’s advice.
> Make DB pool sizes adjustable by connection type

- loader/src/exceptions.js
- loader/src/sources/hyvee/index.js
- loader/src/sources/wa-doh.js
- loader/test/wa-doh.test.js
It turns out we weren't checking for and surfacing error messages from HyVee's GraphQL responses, which led to this confusing error early this morning: https://sentry.io/organizations/usdr/issues/3505575050. We didn't capture much detail because we didn't even realize the response was an error. Now we surface a better error at a more appropriate point.
This is a standard format for errors in GraphQL, so I've just genericized the handling we already had in the Washington Dept. of Health source.
> Check for and handle errors in HyVee responses

- loader/src/sources/prepmod/index.js
Alaska is now surfacing Tdap vaccinations in Prepmod, which we should not be including. Fixes https://sentry.io/organizations/usdr/issues/3382842420.
> Ignore Tdap vaccines in Prepmod

- loader/src/cli.js
- loader/src/sources/albertsons/index.js
- loader/src/sources/cdc/api.js
- loader/src/sources/cvs/smart.js
- loader/src/sources/heb/index.js
- loader/src/sources/hyvee/index.js
- loader/src/sources/kroger.js
- loader/src/sources/prepmod/index.js
- loader/src/sources/riteaid/api.js
- loader/src/sources/riteaid/common.js
- loader/src/sources/riteaid/scraper.js
- loader/src/sources/vaccinespotter/index.js
- loader/src/sources/vts/geo.js
- loader/src/sources/wa-doh.js
- loader/src/sources/walgreens.js
- loader/src/utils.js
- loader/test/albertsons.test.js
- loader/test/cdc.api.test.js
- loader/test/cvs.smart.test.js
- loader/test/heb.test.js
- loader/test/hyvee.test.js
- loader/test/kroger.smart.test.js
- loader/test/prepmod.test.js
- loader/test/riteaid.api.test.js
- loader/test/riteaid.scraper.test.js
- loader/test/vts.geo.test.js
- loader/test/wa-doh.test.js
- loader/test/walgreens.test.js
This fixes some long-standing bad decisions around parsing CLI options and default values in the loader (all my own fault):
- We had lots of repetitive parsing and error-checking code for converting `--states` to an array and validating other options. These always should have been handled up-front in the CLI parsing code, and they now are.
- Now that the parsing and validation is done in one place, I made it a little more detailed and strict.
- Removed the source-specific state options (e.g. `--rite-aid-states`). I originally made these because I expected we’d call the loader with multiple sources and often need to specify different sets of states for each source. We’ve never used it that way in production, though, so there’s really no value in supporting those options.
- Add/allow …
> Clean up CLI parsing boilerplate, allow default `--states`

- loader/src/sources/prepmod/index.js
PCSV13 and PPSV (types of Pneumococcal vaccines) recently started showing up in PrepMod. This ignores them like we do other non-COVID vaccines.
Fixes https://sentry.io/organizations/usdr/issues/3382842420.
> Ignore Pneumococcal vaccines in PrepMod

- loader/src/smart-scheduling-links.js
- loader/src/sources/prepmod/index.js
- loader/test/prepmod.test.js
Sometimes PrepMod data has full addresses in the `address.line` field, despite also having the city/state/etc. fields filled in. This attempts to clean that up automatically where possible, and also address issues where multiple lines are conjoined into one in the data, e.g. `Loussac Library / 3600 Denali St`.
Fixes #458.
This doesn’t seem to be happening with any current data in PrepMod (yay), so I tested against some old examples (and then manually cleaned them up in our system). Some manual fixes:
```
id: a8096272-a874-43a2-8390-7a76f5434a34
from: [ '30 Mall Drive W. Jersey City, NJ 07302' ]
fixed: [ '30 Mall Drive W.' ]
id: be266796-f2ce-422b-a138-4f3912e65f25
from: [ '1 Cedar Crest Village Pompton Plains, NJ 07444' ]
fixed: [ '1 Cedar Crest Village' ]
id: …
```
> Clean up PrepMod addresses during formatting

- server/jest.config.js
- server/test/db.test.ts
- server/test/lib.ts
- server/test/scripts.remove-duplicate-locations.test.ts
Instead of wrapping tests in transactions (and making transactions *inside* the test do nothing), truncate the relevant tables and sequences before each test (not after, so if something goes wrong, that leaves stuff in the DB so you can inspect it).
This also fixes a long-standing issue where Jest would try and run tests in the `dist` directory, which would sometimes lead to incorrect failures (if you hadn’t run a build since changing a test file, the test in `dist` would have the old code and fail).
Fixes #463.
> Allow tests to have transactions

- loader/src/utils.js
Got doesn't have a built-in timeout, so it's possible for an HTTP request the loader makes to hang forever. This sets a default timeout of 2.5 minutes on every request. That's long, but at least makes sure things eventually fail. I think this might help with #669 (the loader occasionally hangs and never stops), although it's possible the root cause is something else.
> Ensure all HTTP requests eventually time out

- loader/src/model.js
- server/src/interfaces.ts
When I was reviewing #122 earlier this week, I noticed some locations had a `MOBILE_CLINIC` location type in the database, even though we don't have constants here for them (they were probably manually set, or came from earlier code, or something to do with Vaccinate the States). This adds a constant for it so we can use it, and so it's clear that it's a valid value, even though we don't actually have any code using it right now.
> Add `MOBILE_CLINIC` location type

- loader/src/cli.js
In #841, I removed the ability to run the loader as a server, but forgot to remove the return value from the main `run` function in the CLI, which was only used for the server. (Noticed this while looking at types as part of #882/#884).
> Remove return values from main CLI function

- loader/src/exceptions.js
- loader/src/smart-scheduling-links.js
- loader/src/sources/cvs/api.js
- loader/src/sources/cvs/scraper.js
- loader/src/sources/cvs/smart.js
- loader/src/sources/kroger.js
- loader/src/sources/njvss/index.js
- loader/src/sources/prepmod/index.js
- loader/src/sources/wa-doh.js
- loader/src/sources/walgreens.js
- loader/src/utils.js
In my experiments on code sharing in #882, I noticed our JSDoc types aren’t always correct or up to date, owing to the fact that they aren’t strictly checked. This fixes up some of the more obvious issues, although it isn’t enough to make the TypeScript compiler happy.
> A little light JSDoc types cleanup

- render.yaml
- server/.env.example
- server/knexfile.js
One discovery from initially deploying to render in #755 was that database connection configuration is a lot of boilerplate, since we don't support a connection URI as a single variable. This fixes that problem. I've updated the Render configuration here, but not bothered with Terraform/AWS since we will be tearing that down shortly.
> Simplify DB connection config on Render

- server/scripts/availability_dump.js
I noticed this whiles tuning the resources this job needs on Render — if the configuration is wrong and the command exits early, it still signals success. That's not good!
> Exit with error code when availability_dump fails

- loader/package-lock.json
- loader/package.json
- render.yaml
- server/package-lock.json
- server/package.json
- server/scripts/availability_dump.js
The loader has used v3 of the AWS SDK since its inception; this upgrades the server to match. Some nice upsides include only updating when there are changes to S3, a promise-focused API (instead of having to do extra stuff to get promises), and built-in TypeScript support.
One downside here is that multipart uploads got more complicated. There’s still first-party tooling, but it’s in a separate package from S3. It also appears that v3 no longer reads the `AWS_DEFAULT_REGION` environment variable, which we’ve been relying on (at least it didn’t work for me when testing). It looks like we should be setting `AWS_REGION` now instead. For the short term, I shimmed in support for the old variable.
> Upgrade server to AWS SDK v3

- render.yaml
I did some quick experiments on Render with a temporary cron job and discovered the bottleneck for the Daily Data Snaphsot is really uploading to S3. There might be some optimization we can do there, but in the mean time, there's no reason to use 2GB of RAM and 1 CPU when less will make no difference in performance.
> Reduce resources for daily data dump job

- server/knexfile.js
This is a follow-on to #902. I tested that change by running the server, but never ran tests with `DB_URL` defined! It, of course, does not work without additional support. D'oh!
> Support DB_URL for tests

- render.yaml
While reviewing the Render deployment with @alexallain last week, he pointed out that the database, while smaller than what we have on AWS, may still be overprovisioned (we use a good deal of RAM, but Postgres allocates a huge chunk by default even when it may not actually be using it, so good stats are more complicated here). If we're going to see whether we can lower the database tier by one, we ought to do it now, before switching production to Render.
**This will probably fail!** On the web console, you can’t downsize a database. If this fails, I’ll try creating a second one that is at `standard plus` tier and then switching things to it.
> Try downsizing the database by one level in Render

- loader/src/cli.js
- loader/src/config.js
- server/src/config.ts
Use `RENDER_GIT_COMMIT` to set the release tag for Sentry, just like we do in the server. Ideally I’ll improve this in #882, but for now, this just needs to be added to the loader.
> Ensure Sentry releases are set on Render Loader

- render.yaml
In preparation for switching production to Render (#779) we are turning off public internet access to the database. This mainly means you can no longer run `psql -d xyz` from your local machine, and will instead need to start a temporary shell or ssh session on one of our Render services to access it.
> Disallow public connections to the DB on Render

- server/src/api/edge.ts
- server/src/app.ts
- server/src/datadog.ts
- server/src/db.ts
- server/src/middleware.ts
This adds a few metrics (and tags for metrics) to track:
- `api.received.updates.count` are the number of calls to the `update` endpoint, tagged by source.
- `api.received.updates.bytes` (histogram) is the uncompressed body size of each update, tagged by source.
- `db.locations.created.count` is the number of locations created in the DB
- `db.locations.updated.count` is the number of locations updated in the DB
- `db.availability.created.count` is the number of availability records created in the DB
- `db.availability.updated.count` is the number of availability records updated in the DB
All the above have a `source:<source_name>` tag, and request metrics now also have a `internal:<true|false>` tag for whether the request came from part of UNIVAF, or from someone else (e.g. state of NJ). …
> Add more metrics to API & DB operations

- terraform/api.tf
> Use HTTPS between CloudFront and external hosts

- .github/workflows/ci.yml
- render.yaml
- terraform/api.tf
- terraform/variables.tf
Since my previous attempt (#930, #932) at making CloudFront point getmyvax.org at Render failed spectacularly, I'm trying this again on a separate test domain (render.getmyvax.org) so we don't have downtime. I think the main issue is just that Render needs DNS pointed directly at it first so it can validate that it's ok to respond to the hostname we're sending it.
Once Render validates, this will need to be followed up my a change to the Route53 record so it points to CloudFront instead.
> Point `render.getmyvax.org` to Render

- terraform/api.tf
This is the follow-up to #933. Render has verified the hostname and issued itself an SSL certificate, so now we can move DNS to point at CloudFront instead.
> Point `render.getmyvax.org` at CloudFront

- server/src/app.ts
Let's see if making the `Cache-Control` directive explicitly allow public caching gets Render's built-in Cloudflare support to cache beyond just DDOS protection. If so, we can drop CloudFront.
> Add public cache directive for Cloudflare

- render.yaml
- terraform/api.tf
This is a redux of #930, now that I know how to do it correctly (see #933, #934, #935). It points the DNS records for our domains directly at Render so Render can validate, issue SSL certificates, etc. Once that's done, I'll issue another PR to point the DNS records back to Cloudfront, and point Cloudfront to Render.
> Point DNS directly to Render

- terraform/api.tf
This is a follow-on to #936, and properly completes what was originally intended in #930. Our DNS records for `getmyvax.org` point to CloudFront, which points to Render.
> Point DNS back to CloudFront

- loader/src/utils.js
- loader/test/utils.test.js
This is kind of ugly, but attempts to handle new bivalent vaccines in a meaningful way when fuzzy matching (this mainly affects PrepMod, where we were conflating bivalent vaccines with normal ones).
Caught by the Anchorage i-Team.
> Fuzzy match new bivalent vaccines properly

- terraform/auto_scaling.tf
- terraform/loaders.tf
This disables all the loaders on AWS and scales down the API service a bit as part of a slow, stepwise shutoff for everything in AWS that we should no longer need. Part of #683/#779.
> Disable loaders and scale down on AWS

- terraform/auto_scaling.tf
- terraform/deprecated/auto_scaling.tf
This is pretty subtle! After turning off the loaders in AWS today (#941), I expected the API to scale down to its minimum, but it did not. At first I thought something must somehow still be sending it data or reaching it for queries, but no, it's actually because we had a lower bound instead of an upper bound set on the downscaling (clearly a copy-paste error). This fixes it and also updates the deprecated configurations so someone referencing them won't make the same mistake.
Hilariously, I had noticed long ago that the API service rarely seemed to scale down (I guess it was actually *never*), but just assumed that was because the time interval it evaluated things over was too long. I clearly should have made more noise about it at the time. (File under: another way the simpler config …
> Fix broken autoscaling configuration in Terraform

- render.yaml
Out of an abundance of caution, we've been waiting until 5am UTC to archive the previous day's data. That's probably a lot longer than we really need to wait, though, so this moves it up to 1am UTC, making our archived data in S3 show up in a more timely fashion and (for everything except logs) more accurately reflect what the DB looked like at the end of the day.
> Move nightly snapshot closer to midnight UTC

- render.yaml
Running the DataDog agent as a separate service (currently recommended by Render) comes with a bunch of caveats, including that it sends a whole raft of system metrics that are pointless, since nothing except the agent is actually run on the system it's gathering metrics for. Making the agent think it's on ECS Fargate using the `ECS_FARGATE` environment variable causes it not to send those. This *may* also remove a `host` from our DataDog account (saving some money), but I haven't seen for sure whether that's true yet.
> Fix a DataDog agent issue with ECS_FARGATE hack

- terraform/api.tf
- terraform/variables.tf
The snapshot task has been suspended for a few days with no issues, so I think it’s time to delete it entirely.
> Remove daily data snapshot task from AWS

- loader/src/sources/heb/index.js
- loader/test/fixtures/nock/h-e-b_should_output_valid_data.json
- loader/test/heb.test.js
H-E-B added bivalent vaccine listings in an unenjoyably complex new way, and this adds support for it. Fixes https://sentry.io/organizations/usdr/issues/3613330687 and https://sentry.io/organizations/usdr/issues/3613330594.
Previously, each locations would have a `slotDetails` field with an array of objects representing the number of open slots for each vaccine type (identified by the `manufacturer` field [side note: this originally indicated just the manufacturer, until we had pediatric vaccines, at which point it became more of a product type]), like so:
```js
{
"slotDetails": [
{
"openTimeslots": 23,
"openAppointmentSlots": 23,
"manufacturer": "Pfizer"
},
{
"openTimeslots": 15,
"openAppointmentSlots": 15,
"manufacturer": "Ultra_Pediatric_Pfizer"
},
{
"openTimeslots": 164, …
```
> Support bivalent vaccines at H-E-B

- loader/src/sources/prepmod/index.js
- loader/src/utils.js
- loader/test/utils.test.js
Alaska's PrepMod instance is now showing "Moderna COVID-19 Vaccine (Ages 12+)" instead of "Moderna COVID-19 Vaccine (Ages 18+)" in a lot of cases now. They are the same product with the same authorization, so not much really needs to change here.
While I was at it, I added the display name to the error message, since this unhelpfully vague error in Sentry is always frustrating:
Fixes https://sentry.io/organizations/usdr/issues/3382842420.
> Handle new Moderna vaccine name from Alaska

- loader/src/sources/prepmod/index.js
Washington's PrepMod instance just started listing `"multi - vaccine"` as a vaccine name on some schedules. This skips over it, which should be perfectly fine since we are only seeing it on schedules that list multiple other vaccines, and we'll pick up the COVID-ness and product names from those. Fixes https://sentry.io/organizations/usdr/issues/3629606210.
> Handle "multi - vaccine" listings in Washington

- loader/src/utils.js
CVS is outputting invalid JSON (there are unescaped tab characters, which are not allowed in proper JSON) in their SMART Scheduling Links API. This escapes any unescaped tabs, which should solve the issue for now on our side. (I've also notified their lead dev about the issue via FHIR chat.)
Fixes https://sentry.io/organizations/usdr/issues/3638566125.
> Fix unescaped tab characters in CVS JSON data

- render.yaml
- terraform/deprecated/loaders.tf
This week, a lot of our cron jobs on Render started failing due to some sort of scheduling issues in Render's orchestration (that is: the jobs are never actually starting and our scripts don't even get a chance to fail -- the orchestrator is scheduling a job, and then failing it several minutes later instead of running it).
This is a check to see if maybe committing more resources to these jobs can solve the problem.
I also dropped the `--states` option from `render.yaml` in places where it was redundant, and just specifying the default.
> Upgrade cron job resources

- loader/src/sources/prepmod/index.js
Washington is now listing MMR vaccines in PrepMod, and we need to ignore those since they are unrelated to COVID.
Fixes https://sentry.io/organizations/usdr/issues/3653923079.
> Handle MMR vaccines listed in PrepMod

- terraform/main.tf
Noticed we are behind while updating AWS stuff. I figured our Dependabot configuration would make this automatic, but apparently not.
> Upgrade Terraform from v1.2.8 to v1.3.2

- terraform/bastion.tf
- terraform/networks.tf
- terraform/variables.tf
This re-instates the old public/private network setup and bastion security group on AWS. I combined all network configuration into a single file this time (makes more sense to me) and tried to add more clearly explanatory comments. I'm not sure I got the network stuff 100% right (this is the part of AWS I have the most trouble with, TBH), but this matches what I understand from the previous comments.
> AWS again: Reinstate networks and bastion

- terraform/db.tf
- terraform/modules/rds/main.tf
- terraform/modules/rds/outputs.tf
- terraform/modules/rds/variables.tf
- terraform/variables.tf
Recreate the database on AWS. This uses smaller default instance and disk size than we used to have, and is in-line with what we were using on Render (which seemed to work just fine). Should save a little on costs.
> AWS again: reinstate database

- .github/workflows/ci.yml
- terraform/api.tf
- terraform/auto_scaling.tf
- terraform/ecs.tf
- terraform/iam.tf
- terraform/modules/task/main.tf
- terraform/modules/task/outputs.tf
- terraform/modules/task/variables.tf
- terraform/outputs.tf
- terraform/security.tf
- terraform/variables.tf
Rebuilds the API service on ECS. This involves a lot of fiddly bits with security groups and policies that I modified *slightly* to see how necessary they are (it may break). There's also a *lot* of room for streamlining and refactoring to clean these up, but I'll leave that for a follow-on change once things are working again.
> AWS again: reinstate API service on ECS

- .github/workflows/ci.yml
- .github/workflows/ui-deploy.yml
We are getting deprecation warnings in our CI workflows. This cleans them up by switching to actionlint (the previous linter we used is no longer maintained, and they recommend actionlint instead).
> Fix deprecation warnings for action-linter

- terraform/iam.tf
- terraform/loaders.tf
- terraform/modules/loader/main.tf
- terraform/modules/loader/variables.tf
- terraform/modules/schedule/main.tf
- terraform/modules/schedule/variables.tf
- terraform/variables.tf
This sets up the loaders. I'm trying something new here by using `for_each` to reduce boilerplate for each loader definition. For starters, I’ve only set up two loaders. I’ll add the rest once I’ve worked out any issues.
If this works well, I think it probably suggests we should rewrite the `loader` module as a `cron` module that can also be used for the Daily Data Snapshot task (i.e. make it about running a task on a schedule, not about loaders specifically). I’ll get to that when doing the Daily Data Snapshot.
> AWS again: reinstate the loaders

- render.yaml
- terraform/modules/task/main.tf
Mark the Sentry environment as either Render or ECS for clarity about where errors are coming from. We did this just for Render when doing the initial switchover, and I'm realizing this is probably just as useful long term anytime we make changes or big shifts.
> Differentiate Render vs. ECS in Sentry

- terraform/api.tf
- terraform/variables.tf
**Depends on #1019, which should land and get tested first.**
This is the last component of a functioning deployment on AWS (besides DNS & CloudFront, which aren't strictly required for things to work).
Once this is in, we should wait for a day and make sure we feel good before switching DNS and CloudFront back over to AWS and turning off Render. This also gives us time to a little messy refactoring on the Terraform code before things are in production, and changes need to be made more carefully.
> AWS again: reinstate daily data snapshot

- terraform/api.tf
- terraform/loaders.tf
Set up https://ecs.getmyvax.org to point to a CloudFront distribution that gives public access to the new old AWS ECS deployment.
> AWS again: set up CloudFront for ECS deploy

- terraform/api.tf
I wasn't paying attention in #1023 and pointed ecs.getmyvax.org to the Render CloudFront instead of the ECS CloudFront.
> AWS again: point ECS domain to correct place

- loader/src/utils.js
- loader/test/utils.test.js
Moderna's new bivalent vaccine has just been approved for for ages 6-11, and is the same product as the one for ages 12+ (just a half dose). Accordingly, some Alaska Prepmod locations are now listing Moderna for "ages 6+", where they previously always differentiated listings for ages 6-11 and 12+ or 18+. This handles "6+" the same as "12+", and separately from ranges starting at 6 (e.g. "6-11").
Fixes https://sentry.io/organizations/usdr/issues/3666320109.
> Handle Moderna for "ages 6+" in Prepmod

- loader/src/cli.js
In #1028, I changed the loader to use the Datadog API instead of the agent. However, the API client we're using doesn't support distributions (yet) and I foolishly used distributions for some of the metrics. I changed their types when switching to the API, but it turns out that while you can change the type of counts/gauges/rates, you can't change between those and distributions. This gives the things that were distributions new names so we can actually see them in Datadog.
> Change names for metrics that were distributions

- terraform/api-autoscaling.tf
- terraform/api.tf
- terraform/variables.tf
Pushing this to GitHub before I’m done for the evening. Probably won’t merge tonight.
This does a little fine tuning on the AWS deployment, based on things I noticed while comparing to Render and doing cleanup before cutting production back over to AWS:
- Ups the database’s disk size to 48 GB. We don’t need remotely that much space, but AWS throttles our disk I/O performance based on disk size, and is going to lock up our maximum performance soon. This increase in disk size *should* give us enough baseline performance to match our workload. *(On the flip-side, we don’t have to do this. We can also live with throttled performance. But this is cheap — it should cost us ~$2 extra per month.)*
- Adjust API scaling thresholds and increase the number of DB connections per API server instance. …
> A little light AWS tuning

- terraform/api-domains.tf
This is cleanup from #1033, and just removes the Terraform `move` blocks that have done their job and are no longer necessary.
> Remove completed Terraform `move` block

- terraform/api-domains.tf
In #1033, I left the aliases in CloudFront set incorrectly. It seems to be working, which is a bit of a surprise, but it's certainly not correct. This fixes it.
> Fix CloudFront aliases

- loader/src/sources/prepmod/index.js
This is a competing proposal with #987.
This fixes #929 by adding line breaks in situations like `", 123 Some Roadname Rd."` and `", PO Box 123"`. It also removes the Sentry warning, since this covers all the cases we've seen over an entire month.
I'm a little on the fence about this, since it involves so much added code for what feels like little benefit. Another reasonable approach here might be to just drop all the stuff here that is re-breaking lines entirely (the core part of the original problem was just to the redundant city/state/zip in the address lines, and this may have gotten out of hand). For example: 856c57c27125f7b96b1db150cdc4654a44a2cbe2
> PrepMod: Add line break in ", 123 somewhere rd"

- render.yaml
- terraform/api-autoscaling.tf
- terraform/variables.tf
One lesson from rebuilding things on AWS is that we just don't use much memory in the API server. We can't reduce RAM without also cutting the CPU in half, but my working theory is that we can just double the instances and it should be fine. We'll follow the charts and see how this goes (honestly I think a baseline of more instances might make the whole thing more stable anyway).
> Use more smaller API server instances

- loader/src/sources/heb/index.js
- loader/test/heb.test.js
This fixes an exception we recently saw in production caused by not accounting for a logical branch where the list of available vaccines might not be set (it's rare to see in practice). Also adds a test for this case.
Fixes https://sentry.io/organizations/usdr/issues/3684116765
> H-E-B: Handle slots for "multiple" in all cases

- docs/runbook/README.md
Somehow I let some excess indenting creep into #1057, which caused a numbered list to be interpreted as a code block!
> Fix broken formatting in deployment guide

- loader/src/api-client.js
I added metrics about retries to the API client a couple days ago (#1056), and while we have seen errors that *should* have been retried (e.g. ECONNRESET, ETIMEDOUT), we've never gotten > 0 retries in our metrics. It's possible that when we've seen these errors, they have always occurred for all 3 tries, but that seems unlikely. My quick thought here is that setting `throwHttpErrors: false` is short-circuiting the retry logic (internally, it might be part of the throw-an-exception logic). This might be wrong! It's an experiment.
> Try not setting `throwHttpErrors: false` for Got

- server/package-lock.json
- server/package.json
Upgrades the AWS SDK components in `/server` to v3.194.0, since Dependabot didn’t do it.
> Upgrade AWS SDK to v3.194.0 in /server

- .github/workflows/ci.yml
- .github/workflows/ui-deploy.yml
- loader/Dockerfile
- render.yaml
- server/Dockerfile
- server/Dockerfile.seed-db
- server/package-lock.json
- server/package.json
Node 18 is now the LTS release, so it's probably time to upgrade to it from 16. There are some changes to Node.js types, but no new JS language features that warrant updating.
> Upgrade Node.js to v18.12.1

- .github/workflows/ui-deploy.yml
I broke the UI deploy workflow in #1133 - I treated it as if it were installed in the main working directory of the CI server, but it's not (because there are *two* checkouts side-by-side in that workflow). This fixes the path from which we run NPM, which should solve the issue.
> Fix UI deploy workflow

- .github/dependabot.yml
In #1133, I switched the repo to using NPM workspaces. I *thought* I made the appropriate changes to our Dependabot config, but it turns out I made some mistakes.
> Fix Dependabot config after code sharing PR

- common/src/vaccines.ts
- loader/src/sources/cdc/api.js
- loader/src/utils.js
- loader/test/utils.test.js
- server/public/docs/openapi.yaml
Prepmod started surfacing vaccine names for Bivalent vaccines for ages 6+ months a few hours ago. This adds the codes, constants, and fuzzy parsing needed to handle it.
Fixes https://sentry.io/organizations/usdr/issues/3798626687
> Support bivalent vaccines for ages 6+ months in Prepmod

- loader/src/sources/hyvee/index.js
We have been seeing a lot of timeouts recently for HyVee (see https://sentry.io/organizations/usdr/issues/3116608217), so I'm trying bumping up the timeout a bit to see if that helps smooth things over.
> Bump up the timeout on HyVee requests

- loader/src/sources/heb/index.js
- loader/test/fixtures/nock/h-e-b_should_output_valid_data.json
H-E-B started surfacing new vaccine codes for bivalent moderna infant vaccines a couple hours ago. Fixes https://sentry.io/organizations/usdr/issues/3804009429.
> Support bivalent boosters for infants at H-E-B

- loader/src/sources/heb/index.js
- loader/test/fixtures/nock/h-e-b_should_output_valid_data.json
H-E-B just added bivalent infant vaccines from Pfizer, although they have a real weird suffix: `_Updated_Dose3` (where all the other types use `_Updated_Booster`). I've added support for this, and, just in case they change it to match the others, also for `_Updated_Booster`.
Fixes https://sentry.io/organizations/usdr/issues/3811243951.
> Support bivalent infant Pfizer from H-E-B

- terraform/api-domains.tf
- terraform/api.tf
- terraform/variables.tf
This covers part of #1181 by making the load balancer speak HTTPS in addition to HTTP. Once it's running, we'll shift CloudFront to using it instead of the HTTP listener. (And then later secure access with a secret header.)
> Support HTTPS in the API load balancer

- terraform/api-domains.tf
- terraform/variables.tf
This is part 2 of #1181, and is a follow-up to #1185. It creates a secret and has CloudFront send it as a header when proxying requests to the API service. (It does not yet make the API load balancer require the secret, since the CloudFront distribution takes a while to change, and we don't want to break the service while that's happening.)
This also fixes a variable description that it turns out I got wrong in #1185.
> Send secret header to API from CloudFront

- terraform/api.tf
- terraform/variables.tf
This locks down the API server's load balancer so that it only forwards requests to the actual service if it has a header with a secret value. CloudFront is already configured to set that header (see #1186), so this effectively allows only requests from CloudFront.
Fixes #1181.
> Only allow requests through CloudFront

- terraform/api.tf
- terraform/variables.tf
This locks down the API server's load balancer so that it only forwards requests to the actual service if it has a header with a secret value. CloudFront is already configured to set that header (see #1186), so this effectively allows only requests from CloudFront.
I tried to do this in #1186 with a wildcard host header, but it turns out AWS rejects that once you actually try and apply it. This approach uses an IP match to allow all IP addresses instead, which I tested in AWS already so it should work.
This also doesn’t set the default rule to block responses, so if this goes wrong, things still work fine.
> Only allow requests through CloudFront, take 2

- terraform/api.tf
This actually blocks traffic that doesn't come from CloudFlare (or otherwise have the secret header) in the API server's load balancer. It also makes HTTP traffic redirect to HTTPS (we were already doing this in CloudFront, but good to do here, too).
Actually completely fixes #1181.
> Actually disallow non-CloudFront API traffic

- terraform/api-domains.tf
- terraform/api.tf
- terraform/loaders.tf
This has been a messy afternoon. I thought I was good to go in #1189, but then realized I had accidentally started blocking the loaders from sending data to the API. This new approach should make sure loaders use HTTPS and the right domain for the load balancer, plus allow them through since they supply a valid API key.
> Actually disallow non-CloudFront traffic, take 2

- terraform/api-domains.tf
We were accidentally swallowing auth-related headers in CloudFlare! We probably never noticed because the loaders (and other data-submitting partners in the past) went direct to the load balancer. (Noticed in the mess with #1190.) At any rate, this resolves the issue, so we could have the loaders talk through CloudFlare now if we wanted.
> Pass auth headers through CloudFlare

- loader/src/sources/hyvee/index.js
HyVee started surfacing appointments with the code `"Pediatric Pfizer Bivalent 3-4"` yesterday afternoon and this adds support for it. There's no change to the cassette recordings for tests because we *stopped* seeing that code shortly after, so making a new recording now wouldn't add it to the test. That said, there's no reason to expect we won't see this again in the future, so it's still worth adding support for. I've also added a version with parentheses to match other styles we've seen from HyVee.
(These are starting to get so varied and non-conventional that I'm beginning to think we should run these through the `matchVaccineProduct()` fuzzy parser instead of keeping a list of exact matches.)
Fixes https://sentry.io/organizations/usdr/issues/3829987637.
> HyVee: support new infant pfizer bivalent code

- docs/runbook/maintenance.md
There are some messy complexities about handling certain dependency updates from Dependabot, as well as properly updating Node.js versions. This adds a new `maintenance.md` doc about how to handle those kinds of changes.
> Add docs about Dependabot and Node updates

- loader/src/sources/prepmod/index.js
Prepmod is now showing the chickenpox vaccine. Fixes https://sentry.io/organizations/usdr/issues/3873901705.
> Ignore chickenpox vaccine in Prepmod

- loader/src/sources/njvss/index.js
NJVSS started surfacing a new name for bivalent pediatric Pfizer. This adds support for it and for Moderna, assuming we'll see it show up with the same naming pattern soon.
Fixes https://sentry.io/organizations/usdr/issues/3884819879.
> Support new NJVSS codes for pediatric bivalent

- terraform/api-domains.tf
- terraform/main.tf
- terraform/s3.tf
This adds a CloudFront distribution to serve data from our "data snaphsots" S3 bucket at `https://archives.getmyvax.org`. The goal here is mainly to prevent people from potentially driving up S3 costs by making requests we can't control or cache against the bucket. (Per @TylerHendrickson’s guidance.)
This is a first step for #1180. After we confirm this is deployed and working, we’ll need to revoke public read access from the S3 bucket.
> Add CDN for archived data in S3

- terraform/api-domains.tf
In #1264, I used Cloud Posse's cloudfront-s3-cdn module to create a CloudFront distribution in front of our data snapshots bucket. It turned out to have some bugs that weren't obvious until trying to actually deploy and create resources. This *should* address those. (We'll see if more show up!)
If there are more deploy problems after this, it might be better to just stop trying to use the Cloud Posse module. :\
> Work around Cloud Posse CDN module bugs

- terraform/s3.tf
The data in the data snapshots S3 bucket is now available via CloudFront at `https://archives.getmyvax.org`, so we are ready to revoke public read access to the bucket. Fixes #1180.
> Revoke public access to data snapshots bucket

- terraform/api-domains.tf
Looks like I need to flip this back on in order for CloudFront to be able to read the bucket now that it's private. Oops!
(This is a follow-on to #1264 and #1267)
> Enable CloudFront to read private bucket

- terraform/s3.tf
Today I learned that multipart S3 uploads can leave the parts behind if they fail, taking up space in S3 even though they don't show up as complete objects (thanks, @TylerHendrickson). Since all streaming uploads and large uploads done using the AWS libraries or CLI are multipart, this applies to all our uploads. This policy should help clean them up. (We've rarely seen failures, but this is still good practice.)
> Clean up failed upload parts in S3

- terraform/s3.tf
At the end of last week, I discovered some bugs with the writing of historical data to out S3 buckets, and while some of those issues are "fixable", others are not because the original data was lost. Having bucket versioning turned on would have allowed us to resolve those issues. (I don’t recall whether this was an oversight or just a foolish decision for efficiency’s sake.)
> Turn on versioning for data snapshots bucket

- server/scripts/availability_dump.js
At the end of last week, I discovered some bugs with how we write historical data to S3, and this should resolve them:
- Check for logs to be written before actually writing log files. Since we clear out old logs (they inflate the database unreasonably), not doing this previously led to us overwriting some valid log files with empty logs because we’d cleared the data for that date!
- Page through *all* objects in S3. The S3 APIs only list up to 1,000 objects, and we now have more than that many log files in the data snapshots bucket. This led to us overwriting recent log files because the script didn’t see that they already existed, and also led to the above issue where we overwrite valid logfiles with empty ones.
> Take more care when writing logs to S3

- terraform/outputs.tf
We no longer have anything deployed in Render or other hosts, so make sure the Terraform configuration can handle removing the remote domain name variable.
> Support removing "Remote" domain name

- terraform/ecs.tf
While cleaning up old Render.com stuff, I noticed that we are incurring serious costs from traffic going through our NAT Gateways on AWS. It's a little hard to tell the actual cause, and I'm wondering how much of it might be coming from the loaders (and whether that's receiving data from external sources or sending formatted data to the API). The Datadog Agent doesn't work very well on our short-lived loader tasks, so I'm turning on Container Insights, which should give us metrics in CloudWatch about the network usage by each container.
> Turn on Container Instights for ECS

- terraform/loaders.tf
- terraform/networks.tf
We're getting pretty extreme Internet Gateway costs that appear to mostly be coming from the amount of data we pull in from outside parties in the loader. This is an experiment to see whether running the loaders in the default subnets avoids some of that cost.
(In #1321 I tried compressing the data we send from the loaders, but when charting the dat in cloudwatch it’s clear that the *vast* majority of costs are data from the public internet. That change improved things, but not in a significant way.)
> Try running loaders on default subnets

- terraform/loaders.tf
- terraform/networks.tf
Looks like the loaders need a security group in the correct VPC! d'oh. (Follow-on to #1322)
> Try running loaders on default subnets, take 2

- terraform/loaders.tf
- terraform/networks.tf
This moves our loaders back onto the UNIVAF VPC, but using the public subnet instead of the private one. In #1322 and #1323, I misunderstood the Internet Gateway vs. NAT Gateway that were operating in our various subnets. What we really needed was for loaders to have public IPs (they always have, it turns out!) and an IG. Our private subnets don't have an IG, and our public networks do (that's *mainly* what makes them private vs. public). The default subnets all have IGs. So really we just need to run the loaders in the UNIVAF VPC's public subnet. The other lesson learned here was that the smart thing in this case is probably to also give them a new Security Group that has no ingress at all (so they can make connections to other services, but not the other way around -- important since …
> Run loaders on UNIVAF public subnets

- terraform/loaders.tf
In #1324, I tried to change the loader security group's VPC, but it turns out that under the hood you can't do that -- Terraform will try to destroy and recreate it. However, things get messy since there are always loader jobs running, and it can't actually do the destroy and recreate while balancing all the dependencies. This gives the security group a new name, which should solve the issue.
> Change loader security group VPC (correctly)

- terraform/ecr.tf
We keep built container images in ECR, but have no lifecycle policy and old images keep accumulating! This sets up a policy to keep only the latest 10 images. I think this is probably plenty — we rarely roll back, and have never needed to do so by more than one build.
(Alternatively, we can expire by date pushed, but I think that means if we ever fully pause development, that could actually expire *every* image, which is not good. Docs: https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html)
> Expire old build images in ECR

- terraform/api.tf
- terraform/loaders.tf
- terraform/security.tf
Step 1 of #1327.
This moves the API server tasks and the daily data snapshot task from our private subnets to our public subnets (we already did this for the loaders). It also adds a security group for cron jobs that is very strict (the daily data snapshot task was using a security group designed for a server, which is not ideal) and can be used by all our cron-job-like tasks. It also creates a new security group for the API service that is more appropriately named for clarity (the old name may be how we wound up using it for the daily data snapshot).
A follow-up change will remove the old security groups once everything has transitioned over to the new ones.
> Move all ECS tasks to public networks

- terraform/db.tf
Step 1.1 of #1327.
In #1328, I changed the security group the API server tasks use, but forgot to give that security group access to the database! This should fix the issue.
> Ensure new API server can talk to DB

- terraform/db.tf
Step 3 of #1327. Now that we've rejiggered our security groups, we need to stop using them. After this applies, then we can actually delete them.
> Stop using deprecated security groups

- terraform/loaders.tf
- terraform/security.tf
Step 4 of #1327 (final step!). This cleans up Terraform and removes the security groups we deprecated in earlier steps.
> Remove deprecated security groups

- terraform/db.tf
This is a follow-on to #1329 and part of #1327. When I created a new security group for all cron job tasks and made the daily data snapshot task use it, I forgot to give it access to the DB.
This is a little broad — it gives the loaders DB access, but I think I’m ok with that. (Alternatively, we could go back to having separate security groups for loaders and the daily data snapshot.)
> Give cron jobs access to database

- terraform/ecs.tf
We turned on container insights last week to get a better sense of the network usage issues around NAT Gateways. We've resolved those issues, so it makes sense to turn off container insights now (it more than doubles our CloudWatch bill — from ~$0.75/day to ~$2/day).
Fixes #1327.
> Disable ECS Container Insights

- common/jest.config.js
- loader/package.json
- loader/test/walgreens.test.js
- server/jest.config.js
Jest recently added an option to randomize the order of tests. In general, that's a good practice that can help ensure we make tests more independent and robust, so we should be using it.
Fixes #1345.
> Randomize test order

- terraform/api.tf
- terraform/variables.tf
On AWS, we can almost certainly handle more DB connections per instance than we are currently using (in general the RDS DB is better resourced and can handle more connections than the one on Render), so we should bump up the number of connections for better throughput. This also makes the pool sizes configurable, since this seems like something that should obviously be tunable.
Note this eliminates the custom pool size from the daily data snapshot job. I'm not sure when we added that, but I suspect I might have done it accidentally while thinking I was adjusting the API server task. In any case, it shouldn't really need many connections, since it just makes one query at a time and streams the results out.
> Boost DB connection pool size for API

- terraform/api.tf
We used to have the load balancer redirecting from `www.getmyvax.org` to `getmyvax.org`, but it looks like I must have broken that at some point when adding CloudFront, or during the Render.com mess. The rule wound up attached to the HTTP listener (not the HTTPS one), and since CloudFront handles the HTTP → HTTPS redirect, a request that would trip that rule never makes it to the load balancer. Moving it to the HTTPS listener (where it always should have been) fixes the issue.
> Fix www subdomain redirect

- terraform/modules/rds/main.tf
This fixes a deploy error from #1349. Apparently you can’t use quotes in descriptions.
> Fix security group name in RDS

- terraform/db.tf
In #1349, I flipped how security groups work with RDS, and services that need access to the DB now include a security group that the DB outputs. We no longer need to specify allowed services as inputs.
> Remove no longer needed DB ingress security

- terraform/api-autoscaling.tf
Somehow (probably in the mess with Render) we got our autoscaling rules twisted backwards so that the alarms were never scaling things up or down! This fixes the issue (after lots of reading the scaling docs).
> Fix backward autoscaling rules

- loader/src/sources/prepmod/index.js
Alaska's PrepMod instance started listing HPV and Hepatitis vaccines, which we should be ignoring.
Fixes https://usdr.sentry.io/issues/4006034995/ and https://usdr.sentry.io/issues/4006034980/
> Ignore HPV and Hepatitis in Prepmod

- terraform/cron-loaders.tf
A couple weeks ago I shrunk the API servers and that caused them to start dropping requests (totally manageable; the loaders retry and never experienced any failures as a result). Reducing the concurrency appears to help alleviate the issue without adding more resources.
It’s also not making the jobs take any longer! Here’s a chart of loader duration (includes some time before and after I made this change ad-hoc to test it):
And retries in the loader:
This has also reduced 95th percentile response times a bit (not dramatic, but it is clear in the charts).
---
On the other hand, it does not appear to have reduced our CPU usage (it maxes in the upper 90%s regularly), which suggests we have some CPU-constrained stuff going on, and needs further investigation. (Likely culprits: validating …
> Reduce concurrency for CVS, Walgreens

- server/src/api/edge.ts
- server/src/db.ts
- server/src/tracing.ts
- server/test/support/globalSetup.ts
This uses Sentry's tracing support to add some more spans around various operations (mostly in the update path) so we get more detailed traces. There's a lot "seems like it should be built in" utility tooling I had to write here, which was a bit disappointing.
It’s messy, and makes some of our code more complex (returning early is hard, as you can see in the “updateAvailability” route handler), and I’m not 100% sure this was totally worthwhile. Gonna let it sit for a while. May throw it out. 🤷 
Before:
After:
> Add more detailed tracing for Sentry

- loader/src/sources/riteaid/scraper.js
In #1370 and #1371, I changed the Rite Aid Scraper to use a variable radius for each zip code that it queries, but forgot to use the correct radius when issuing a second query for the details of each location (we issue one query for a list of locations, and then the same query again with slightly different arguments to get the details about available slots at those locations).
Should hopefully fix https://usdr.sentry.io/issues/4015111034/
> Use correct radius to load Rite Aid details

- loader/src/sources/riteaid/scraper.js
In #1382, I fixed an issue that was causing us to see query results in the Rite Aid scraper that were too big because we were using the wrong radius when loading detailed results. Since landing that, however, we've seen this error happen several times on the first, non-detailed query! (Before, I checked the last 15 occurrences and they were *only* on the second, detailed query... hmmmm.)
In all the cases I looked at, the number of known Rite Aid locations within the search radius was *way* fewer than 100, so I'm not sure what's going on. My best idea at this point is to add more telemetry, so that's what I've done here. When we send this error to Sentry, we'll include a list of all the results and their distances.
> Send more info when Rite Aid queries are too big

- loader/src/sources/riteaid/scraper.js
The rate limit for the Rite Aid scraper has been erroneously applied just to the initial "summary data" requests, and not to the secondary "detailed" requests for slot-level info. That's a mistake! We are getting a few 403 (forbidden) responses to the scraper's requests every hour, and remembering to apply the rate limit to all requests is likely to help here.
Note this is likely to make the run-time of the scraper a bit slower (it currently averages right around 6 minutes), but that should be OK. Separately, I think we might want to consider running the scraper less often — it currently runs more often than the officially supported API source (every 10 minutes vs. every 30), which I think is a relic of times when it was critical to get frequent, detailed info (the scraper is *much* more …
> Apply rate limit to all Rite Aid scraper requests

- loader/src/sources/riteaid/api.js
- loader/src/sources/riteaid/common.js
- loader/src/sources/riteaid/scraper.js
- loader/test/riteaid.api.test.js
The Rite Aid API and scraper sources both occasionally encounter a raft of 403 status codes and fail (anywhere from 1/hour to 1/day). Under the assumption that we’re hitting a rate-limiting/abuse measure, this change sets us up to retry those requests rather than failing immediately, but with a greater than usual delay.
This is an experiment! It might not fix the issue — an equally likely possibility is that because we run on Fargate, each loader run comes from one of a wide set of IP addresses, and some of them have been blocked by Rite Aid. If that's the case, retrying won't do us any good. (OTOH, it should be obvious that this is the case if the change here has zero impact on the rate at which we see errors, and then we take appropriate action, like logging clearer errors and failing …
> Retry Rite Aid requests on 403 status codes

- loader/src/sources/riteaid/api.js
- loader/src/sources/riteaid/common.js
- loader/src/sources/riteaid/scraper.js
I made a mistake in #1397 by assuming every time the `calculateDelay` function runs for retries, the error involved an actual HTTP response. Some are network problems where the client is unable to communicate with the server at all. (I tested 403 responses, but did not test this!)
This also consolidates the logic in one spot, since it was obviously more complicated than I gave it credit for (I didn’t bother before since it was experimental. That was wrong.).
Fixes https://usdr.sentry.io/issues/4048563618
> Fix Rite Aid 403 retry exception

- loader/src/sources/prepmod/index.js
Ignores vaccines for Rotavirus, DTaP, Meningococcal (Group B and Conjugate), and Hib. Fixes:
- https://usdr.sentry.io/issues/4062141336
- https://usdr.sentry.io/issues/4062141337
- https://usdr.sentry.io/issues/4062141340
- https://usdr.sentry.io/issues/4062141370
- https://usdr.sentry.io/issues/4062141404
> Handle several new non-COVID vaccines in Prepmod

- common/src/exceptions.ts
- common/src/utils.ts
- loader/src/cli.js
- loader/src/exceptions.js
- loader/src/schema-validation.js
- loader/src/sources/riteaid/api.js
- loader/src/sources/riteaid/common.js
- loader/src/sources/riteaid/scraper.js
- loader/test/riteaid.api.test.js
- server/src/exceptions.ts
This reverts #1397 and ensures we bail out early in the Rite Aid API if we hit auth errors. We previously kept trying other states on auth errors because requests for states with no stores would return 401 or 403 status codes (!), and we wanted to be robust against that. However, Rite Aid has started blocking some of the IP addresses for the Fargate machines we run on, so we occasionally get all our requests blocked with auth errors. (We’ve also added an allowlist of states supported by Rite Aid, so the case where we request a state with no stores is pretty hard to hit now).
This approach lets us stop early and better manage rate-based ignore rules in Sentry (we don’t get blocked on most runs, so as long as the rate of failing runs doesn’t get too high, it’s fine).
While I was at it, I …
> Clean up Rite Aid auth error handling

- terraform/cron-loaders.tf
We've had the Rite Aid Scraper running every 10 minutes and the API source running every 30 for a long time, largely owing to the fact that the main API was lacking detailed information we wanted from the scraper, and because the scraper was actually reasonably speedy compared to the API. These days, we no longer need as detailed or up-to-date info and the scraper has become much slower (see #1370, #1371, #1396). The scraper is expensive to run for both us and Rite Aid, so I’m turning down to every 30 minutes (and running the API slightly more often).
While I was at it, I also lowered the API concurrency for all loader jobs. I did this a while ago just for CVS and Walgreens to try and reduce retries and other internal errors. It worked, and did not even make the loaders any slower like …
> Rebalance rite aid loaders

- loader/src/sources/prepmod/index.js
Alaska is apparently now scheduling Polio vaccines (!) through Prepmod, which are out of scope for us. Fixes https://usdr.sentry.io/issues/4084081193/
> Ignore Polio vaccines in Prepmod

- loader/src/sources/cdc/api.js
Novavax is apparently now shipping in smaller vials (5 doses instead of 10), which means it gets a new set of NDC codes. We started seeing these at a few locations today.
I also went through to make sure there weren’t any other new NDC codes, but didn’t see any.
Fixes https://usdr.sentry.io/issues/4123482637/
> Add new Novavax NDC codes

- terraform/cron-loaders.tf
The Alberstons loader source reads data from MHealth, but Albertsons has finally switched from MHealth to their own booking system for COVID vaccines, and all the data in the API we were querying is now stale and irrelevant. We probably should write a new scraper (see #1460), but in the mean time, we should disable the existing one.
> Disable current Albertsons source

- .gitignore
- loader/src/sources/njvss/index.js
- loader/src/sources/walgreens.js
- loader/test/fixtures/njvss.fixture.csv
- loader/test/fixtures/nock/njvss_should_output_valid_data.json
- loader/test/njvss.test.js
NJVSS output didn’t used to set `<location>.availability.valid_time`, and now it does. We've had a note about needing to do this for a long time, and now it's needed to support #1459.
I wanted to add tests, which necessarily meant doing some other minor cleanup of the NJVSS source (using modern `external_ids` formatting, removing the no-longer-necessary random ID generation code). Check the first commit (398488a807112e1666ef7fef0239de0da95a15e7) to see just the meaningful changes here.
There are some other quick changes this points to for NJVSS, but those are slightly more risky (outside the `valid_at` stuff, everything here is pure refactor and does not change behavior). I’ll do them in a separate PR.
> Add `valid_time` to NJVSS Output

- terraform/cron-loaders.tf
New Jersey is no longer frequently updating their data, so it probably doesn’t make sense to run the NJVSS loader especially frequently anymore.
> Reduce NJVSS rate to every 15 minutes

- loader/src/sources/albertsons/scraper.js
- server/migrations/20230508183648_remove_albertsons_specialized_booking_urls.js
In mHealth Coach, some locations would have different booking URLs for different products (or sets of products). The way those worked in mHealth Coach kept evolving, so we added an ad-hoc system for supporting multiple booking URLs as properties of a location's `meta` field (why didn't we do this as part of the *availability* object's `meta` field? I do not remember. It seems like it would have made more sense.). You can see how that was done here: https://github.com/usdigitalresponse/univaf/blob/a73e3912f36cd5a92b8069695e6149acb784d667/loader/src/sources/albertsons/mhealth.js#L163-L172
and here: https://github.com/usdigitalresponse/univaf/blob/a73e3912f36cd5a92b8069695e6149acb784d667/loader/src/sources/albertsons/mhealth.js#L549-L566
Since Albertsons no longer uses mHealth Coach and …
> Remove specialized Albertsons booking URLs

- loader/src/cli.js
- loader/src/stale.js
- loader/test/stale.test.js
On each loader run, send metrics about stale data to Datadog and log warnings. This also adds a command-line option to filter out stale data from the result set, too. A record's age is based on the older of `availability.valid_at` and the latest `availability.capacity` entry or latest `availability.slots` entry (sometimes `valid_at` turns out to be a lie, so we use the actual slots or capacity when we can).
The two added CLI options:
- `--filter-stale-data` will cause the loader not to output/send location records that are stale.
- `--stale-threshold N` sets the threshold (in milliseconds) at which stale data is filtered out or warnings are logged. (Metrics are sent to Datadog regardless of the threshold.)
In all cases, metrics are sent to Datadog (as long as Datadog is configured), …
> Track and filter stale data

- server/.env.example
- server/public/docs/index.html
- server/public/docs/openapi.yaml
- server/src/app.ts
- server/src/config.ts
- server/src/middleware.ts
- server/src/smart-scheduling-routes.ts
- server/src/utils.ts
USDR has decided to shut the service down in a month, so this adds shutdown notices to the docs page and to API responses (using the `Sunset` header and the sunset `Link` header from [RFC 8594](https://datatracker.ietf.org/doc/html/rfc8594).
While I was at it, I moved some middleware function to the right place (since I was messing with middleware to do the headers) and cleaned up some URL logic by adding an `absoluteUrl(relativeUrl, request)` utility function.
> Add shutdown notices to docs and API responses

- terraform/cron-loaders.tf
It's time to make some more loader adjustments as we ramp down the service and deal with some sources that have gotten stale or stopped working:
- The CVS and Kroger SMART loaders have stale data or fail frequently, so this slows them both down. We only really want to bother with them so we get notified if they start working again at some point.
- Slow down WA state Dept. of Health and Prepmod, since they are high load, not run by commercial entities, and are less critical.
- Disable the Rite Aid SMART loader, since it didn't actually pan out (see https://github.com/usdigitalresponse/univaf/issues/159#issuecomment-1518109902).
Finally, this makes use of the new stale data filtering feature from #1480 to reduce internal traffic.
> Slow down some loaders, stop Rite Aid SMART

- terraform/api.tf
- terraform/variables.tf
This actually turns on the API sunset headers. It should have been part of #1488, but I forgot it.
> Set sunset date for the API in Terraform

- terraform/cron-loaders.tf
The scuttlebutt from a Kroger developer who is no longer working on their API is that the team intentionally decided to turn it off (without notifying any government partners), so we probably shouldn't expect it to come back at this point. CVS's data is also so old I'm sure we're seeing something similar. This turns down the schedules for them to only run 4 times a day, since we don't expect to get meaningful data. At this point, they're just there to notify us if they somehow stop failing.
> Turn CVS and Kroger schedules WAY down

- loader/src/sources/njvss/index.js
Looks like some new names started showing up in NJVSS data. This just adds mappings for them, which are pretty straightforward. Fixes:
- https://usdr.sentry.io/issues/4208283556/
- https://usdr.sentry.io/issues/4208283564/
- https://usdr.sentry.io/issues/4208283628/
- https://usdr.sentry.io/issues/4208283585/
> Add new vaccine names for NJVSS

- loader/src/index.js
- loader/src/sources/kroger/smart.js
- loader/src/sources/wa-doh/wa-doh.js
- loader/src/sources/walgreens/smart.js
- loader/test/kroger.smart.test.js
- loader/test/wa-doh.test.js
- loader/test/walgreens.test.js
This is just a little cleanup refactor so that all sources are structured the same. I also have some bits of uncommitted code that's been floating around on my local drive for a while that goes along with some sources that previously weren't in directories, and since I'd like to commit it for posterity, having a directory to put it in is nice.
> Make sure all loader sources are directories

- common/src/address.ts
- common/src/exceptions.ts
- common/test/address.test.ts
- loader/src/exceptions.js
- loader/src/utils.js
- loader/test/utils.test.js
- server/scripts/availability_dump.ts
- server/scripts/merge-locations.ts
- server/scripts/remove-duplicate-locations.ts
- server/src/JSONStream.d.ts
- server/src/stream.d.ts
- terraform/cron-data-snapshot.tf
This does a little not-entirely-necessary cleanup by finally making the server scripts TypeScript, which also lets us move a bunch of duplicated code to the `univaf-common` module more easily. We can also now use the same tools for databases in the scripts as in the main server.
Fixes #199.
> Make server scripts TypeScript, remove duplicated code

- terraform/cron-loaders.tf
- terraform/variables.tf
As we move towards shutdown, this simplifies the service to using only one availability zone and reduces the loader schedules so that none run any more often than every 15 minutes.
> Slim down the production service

- .eslintrc.js
- server/test/api.edge.test.ts
The `/locations` and `/locations.ndjson` should behave the same and mainly differ in their output format, so we should run the same tests against them. Not really necessary but feels nice to finally fix. 🤷
Fixes #276.
> Use same tests for locations JSON and NDJSON

- loader/src/sources/prepmod/index.js
This is a follow-up to #1525 and fixes a typo in a call to `logger.warn()`.
Fixes https://usdr.sentry.io/issues/4219367729/
> Fix new logger call in Prepmod

- loader/src/sources/prepmod/index.js
Alaska's Prepmod instance is now showing "Td", which is a Tetanus/Diptheria shot, so we should ignore it.
This was the actual underlying issue that triggered #1527: https://usdr.sentry.io/issues/4219585851/
> Support new "Td" vaccine in Prepmod

- loader/src/sources/prepmod/index.js
A bunch of new vaccines showed up in Prepmod Friday afternoon, and this ignores the non-COVID ones. Fixes:
- https://usdr.sentry.io/issues/4224421573/
- https://usdr.sentry.io/issues/4224421564/
- https://usdr.sentry.io/issues/4224421558/
- https://usdr.sentry.io/issues/4224421556/
> Ignore more new vaccines from Prepmod

- loader/src/exceptions.js
- loader/test/exceptions.test.js
GraphQL error responses are a list of N errors, and we often see the same error repeated multiple times (for example, this one from this morning is just the same "internal server error" message repeated 280 times: https://usdr.sentry.io/issues/4228325474/events/b3e7cf68182e4786b5a660d835880367/). To keep errors readable, our GraphQlError class now dedupes repeated messages.
For example, instead of this error:
GraphQlError: Internal Server Error, Internal Server Error, Internal Server Error, Internal Server Error...
We'll now see:
GraphQlError: Internal Server Error (×280)
This also makes some minor improvements to the JSDoc types for GraphQlError.
> Clean up duplicative GraphQL error messages

- loader/src/sources/walgreens/smart.js
- loader/test/walgreens.test.js
Walgreens's SMART Scheduling Links API now requires some extra querystring fields in order to access it. This isn't private info — it's really just an implementation detail that's chanaged with Azure Blob Storage.
Fixes https://usdr.sentry.io/issues/2420647478/
> Update Walgreens SMART URL

- loader/src/smart-scheduling-links.js
Walgreens's SMART SL manifest file currently lists the slots as a nested array of output items inside the main `output` array, which is not correct, and has been causing us to list all Walgreens as unavailable.
For example, we are seeing a manifest like:
```js
{
"transactionTime": "2023-06-06T03:21:31.360Z",
"request": "...",
"output": [
{ "type": "Location", "url": "..." },
{ "type": "Schedule", "url": "..." },
// These items should not be in a sub-array; they should just be in the `output` array directly.
[
{ "type": "Slot", "url": "...", "extension": { "state": ["AK"] } },
{ "type": "Slot", "url": "...", "extension": { "state": ["AL"] } },
// etc...
]
]
}
```
This hacks in a quick fix: we just flatten the `output` array before handling it. I've also alerted the maintainer of the …
> HOTFIX: Support nested arrays in Walgreens

- loader/src/smart-scheduling-links.js
- loader/test/smart-scheduling-links.test.js
We recently had the Walgreens SMART Scheduling Links API break (#1544), and only found out about it because I happened to be looking into some unrelated errors that I thought were happening with Walgreens (they were not) and noticed some fishy output. That's not good, so this adds schema validation to the SMART Scheduling Links utilities, which would alert us to this issue if it happened again.
This also removes yesterday's hotfix for the Walgreens issue, since it already got fixed at the source! It's nice when some providers are quick and attentive. :)
Fixes #1545.
> Validate schema for SMART SL data

- server/migrations/20230606194142_remove_deprecated_provider_location_fields.js
- server/scripts/merge-locations.ts
The `provider_locations` table has `id_old` and `external_ids_old` fields that have been deprecated and irrelevant for a long time (so long that they are empty for most location records!). This migration drops those columns so they don't show up in historical data dumps and aren't confusing to future folks who might want to fork the project.
> Drop deprecated provider_locations fields

- loader/src/utils.js
- loader/test/utils.test.js
We started seeing new all-ages listings for Moderna in Prepmod today (the FDA authorized a single formulation of Moderna for all ages in April) that weren't fuzzy matching correctly. This adds support for the new vaccine name.
Fixes https://usdr.sentry.io/issues/4234804919/
> Add support for all-ages Moderna in Prepmod

- .github/dependabot.yml
Since we are shutting things down here, normal Dependabot updates are no longer relevant. This disables them (setting `open-pull-requests-limit: 0` is weird, but it is the officially recommended solution).
> Shutdown: Disable Dependabot version updates

- terraform/cron-loaders.tf
Schedule all loaders so they automatically stop running as of 11pm UTC (4pm Pacific) on June 15.
Part of #1550.
> Shutdown: Stop loaders before 2023-06-16

- terraform/api-domains.tf
- terraform/main.tf
We use a Terraform module that isn't yet compatible with v5 of the AWS provider, and this adds a note about the situation, since it might not be clear to someone coming in fresh to the codebase. Hopefully Cloudposse will update the module we use, but it doesn't look like that's coming soon, given that they recently updated their tutorials to specify AWS < 5. (See https://github.com/cloudposse/tutorials/pull/21#discussion_r1219948021)
> Add note about AWS Terraform provider version

- terraform/api-domains.tf
- terraform/variables.tf
This updates DNS to send API server traffic to our new tombstone page (see #1569). Once this is done and propagated, I'll start shutting down production services.
Part of #1550.
> Shutdown: Replace the API with a tombstone

- terraform/api-domains.tf
The previous change (#1571) did not take when Terraform applied it. Hopefully changing the resource name (so we delete the previous record and create a new one) works.
The specific error was:
> Error: updating Route 53 resource record sets: InvalidChangeBatch: [RRSet of type CNAME with DNS name getmyvax.org. is not permitted at apex in zone getmyvax.org.] status code: 400, request id: 14b91d13-0fc8-4e6f-b70c-606f403e8965
> with aws_route53_record.api_domain_record[0]
> on api-domains.tf line 38, in resource "aws_route53_record" "api_domain_record":
So it may also turn out that we can't use a CNAME here in Route 53, but that seems surprising. We’ll see.
Part of #1550.
> Shutdown: Replace API with tombstone, 2nd try

- terraform/api-domains.tf
- terraform/variables.tf
Replace apex DNS record with A records for GitHub pages (docs: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site). This should fix things after #1571 and #1572.
TIL I learned you technically are not supposed to have CNAME records for apex domains, despite the fact that I've done this on other providers in the past! (Now I’m curious whether those providers are automatically resolving IP addresses under the hood, or if most clients are just tolerant of you doing this.)
Part of #1550.
> Shutdown: Replace API with tombstone, 3rd try

- terraform/api-domains.tf
- terraform/outputs.tf
The `getmyvax.org` and `www.getmyvax.org` domains no longer point to CloudFront, so we can get rid of it and the old `ecs.` subdomain.
Part of #1550.
> Shutdown: Remove CloudFront and DNS for API

- tombstone/404.html
This adds some fancy statistics about overall performance and results of UNIVAF to the tombstone page.
Part of #1550.
> Shutdown: Add boastful stats to the tombstone

- .github/workflows/ci.yml
We had some ignore paths set for pushes but not PRs. These shouldn't have gotten out of sync.
> Fix missing ignore paths in CI workflow

- archives/docs/index.md
Fixes a bone-headed typo in a last-minute addition to the archives docs.
> Fix typo in UNIVAF start date

- terraform/ecr.tf
#1581 did not succeed because the ECR repositories are not empty. I think we need. to set `force_delete` on them, *then* delete them. But first we'll see if restoring the configuration is going to cause Terraform to try and recreate them, or if it just puts things back into a good state.
If it causes Terraform to try and recreate them, I'll close this and just delete them manually.
> Shutdown: Prep ECR for deletion

- terraform/s3.tf
Follow-on to #1585. Not sure why we weren't using this variable before. But we're using it now!
Part of #1550.
> Shutdown: Use S3 bucket name variable

- Dockerfile
The changes in #1591 caused the CI pipeline to try and build a new release (even if it doesn’t deploy anymore), but it turns out that the passage of time has broken our Dockerfile. Specifically, the first thing the Dockerfile does is try and update NPM to the latest version (usually a good practice), but the latest NPM is no longer compatible with the version of Node.js that the Dockerfile uses.
Since this project is effectively shut down and not actively maintained, I went ahead and removed the step that updates NPM so this won't happen again. For good measure, I also updated the base image to the latest Node.js 18.x release just in case.
This supersedes #1592.
> Allow Dockerfile to build again
